"""The model registry, embedded as code.

The wheel ships **no** data files, so the registry cannot be read from a ``data/models.json``
next to the package -- under ``pip install`` there is no such file, and the previous
implementation's fallback of sniffing ``Path.cwd()/"data"/"models.json"`` was worse than the
failure: it let a stranger's unrelated ``./data/models.json`` decide which models Modelpin
believes exist.

``data/models.json`` still lives in the repo, because community PRs edit JSON more comfortably
than they edit Python. It is the file to edit; the block below is GENERATED from it by
``python scripts/registry_check.py --sync`` and ``tests/test_watcher.py`` asserts the two are
identical, so the copy here cannot drift from the one contributors send patches against.

``REGISTRY_NOTE`` is the JSON's ``_note``: the registry's own rule file (scope, sourcing, how
conflicting vendor dates are resolved, what is deliberately not transcribed). It is mirrored
here because a pip-installed user never sees the JSON but does see every entry's ``notes``,
which those rules govern. Every entry carries the vendor page it was read from and the day it
was read; ``modelpin.models.Model`` refuses one that does not (MP-276). Every field is one
``mp watch`` or ``mp check`` reads; no comparative field is ever added (ADR-0009).
"""

from __future__ import annotations

from typing import Any

# --- BEGIN SEED (generated by `python scripts/registry_check.py --sync` from data/models.json; edit the JSON, never this block) ---
REGISTRY_NOTE: str = (
    "Schema 2. Scope: text/chat ids a Modelpin scenario can replay, transcribed from the vendor "
    "sections named per entry; audio, realtime, transcription, video, embedding and fine-tuned "
    "(ft-*) rows are out of scope, and several vendor sections are not yet transcribed, so an id "
    "can be absent without being safe: `mp watch` reports an id it does not know as unknown, "
    "never as clear. Image and audio ids that share a table with chat ids are carried with a "
    "`modality` so no chat check is ever suggested for them. Every entry names the vendor page it "
    "was read from (source_url) and the day it was read (fetched_at); modelpin.models.Model "
    "refuses an entry without both. Dates are the vendor's own, transcribed the day the page was "
    "fetched, never recalled. Where two Google surfaces publish different dates for one id, the "
    "entry carries the EARLIER date, the one that removes access first, and quotes the other "
    "surface in notes; where one surface's current lifecycle table and an older release note "
    "disagree, the current table is carried and the note quoted. Anthropic dates are the Claude "
    "API's own: the page states that partner platforms (Amazon Bedrock, Google Cloud/Vertex AI) "
    "set their own schedules, so they can differ on the Vertex path Modelpin supports. Every "
    "field on an entry is one `mp watch` or `mp check` reads; no comparative field (price, "
    "context window, benchmark) is added, because the registry catalogues lifecycle, never "
    "quality (ADR-0009). The OpenAI page's six ft-* rows (five in the fine-tuned-versions table, "
    "one in the snapshot table) are not transcribed: they are not callable ids. The "
    "pre-2026-09-17 placeholders gpt-5.2 and gpt-5.5 were self-declared UNVERIFIED and appeared "
    "on none of the six vendor pages fetched on 2026-09-17; they were removed, and the dated "
    "snapshots behind those aliases were added on 2026-09-18 from their model pages. "
    "modelpin/watcher/registry.py mirrors the models array; regenerate it with `python "
    "scripts/registry_check.py --sync`."
)
SEED_MODELS: list[dict[str, Any]] = [
    {
        "id": "gpt-5.4-cyber",
        "provider": "openai",
        "family": "gpt-5.4",
        "status": "deprecated",
        "deprecated_at": "2026-09-11",
        "retired_at": "2026-10-01",
        "replacement_id": "gpt-5.6-cyber",
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Section '2026-09-11: GPT-5.4-Cyber': 'The gpt-5.4-cyber model is deprecated and "
        "will be removed from the API on October 1, 2026. Migrate to gpt-5.6-cyber before "
        "the shutdown date.'",
    },
    {
        "id": "gpt-3.5-turbo-0125",
        "provider": "openai",
        "family": "gpt-3.5",
        "status": "deprecated",
        "deprecated_at": "2026-04-22",
        "retired_at": "2026-10-23",
        "replacement_id": "gpt-5.6-terra",
        "aliases": ["gpt-3.5-turbo", "gpt-3.5-turbo-completions"],
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Section '2026-04-22: Legacy GPT model snapshots', column 'Substitute model'.",
    },
    {
        "id": "gpt-4-0613",
        "provider": "openai",
        "family": "gpt-4",
        "status": "deprecated",
        "deprecated_at": "2026-04-22",
        "retired_at": "2026-10-23",
        "replacement_id": "gpt-5.6-sol",
        "aliases": ["gpt-4", "gpt-4-0613-completions", "gpt-4-completions"],
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Section '2026-04-22: Legacy GPT model snapshots'.",
    },
    {
        "id": "gpt-4-1106-preview",
        "provider": "openai",
        "family": "gpt-4",
        "status": "deprecated",
        "deprecated_at": "2026-04-22",
        "retired_at": "2026-10-23",
        "replacement_id": "gpt-5.6-sol",
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Section '2026-04-22: Legacy GPT model snapshots'. The same page also lists this id "
        "under 'Past deprecations -- 2025-09-26: Legacy GPT model snapshots (March 2026 "
        "shutdown)': 'Access to these models was shut down on March 26, 2026.' The page "
        "contradicts itself; the later, upcoming row is carried and the earlier one is "
        "recorded here.",
    },
    {
        "id": "gpt-4-turbo",
        "provider": "openai",
        "family": "gpt-4",
        "status": "deprecated",
        "deprecated_at": "2026-04-22",
        "retired_at": "2026-10-23",
        "replacement_id": "gpt-5.6-sol",
        "aliases": ["gpt-4-turbo-2024-04-09", "gpt-4-turbo-completions"],
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Section '2026-04-22: Legacy GPT model snapshots'.",
    },
    {
        "id": "gpt-4.1-nano",
        "provider": "openai",
        "family": "gpt-4.1",
        "status": "deprecated",
        "deprecated_at": "2026-04-22",
        "retired_at": "2026-10-23",
        "replacement_id": "gpt-5.6-luna",
        "aliases": ["gpt-4.1-nano-2025-04-14"],
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Section '2026-04-22: Legacy GPT model snapshots'.",
    },
    {
        "id": "gpt-4o-2024-05-13",
        "provider": "openai",
        "family": "gpt-4o",
        "status": "deprecated",
        "deprecated_at": "2026-04-22",
        "retired_at": "2026-10-23",
        "replacement_id": "gpt-5.6-sol",
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Section '2026-04-22: Legacy GPT model snapshots'. This snapshot only; the page "
        "lists no other gpt-4o snapshot for this date.",
    },
    {
        "id": "gpt-image-1",
        "provider": "openai",
        "family": "gpt-image",
        "status": "deprecated",
        "deprecated_at": "2026-04-22",
        "retired_at": "2026-10-23",
        "replacement_id": "gpt-image-2",
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Section '2026-04-22: Legacy GPT model snapshots'. Listed because the id appears in "
        "the same table; Modelpin does not compare image output.",
        "modality": "image",
    },
    {
        "id": "o1-2024-12-17",
        "provider": "openai",
        "family": "o1",
        "status": "deprecated",
        "deprecated_at": "2026-04-22",
        "retired_at": "2026-10-23",
        "replacement_id": "gpt-5.6-sol",
        "aliases": ["o1"],
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Section '2026-04-22: Legacy GPT model snapshots'.",
    },
    {
        "id": "o1-pro-2025-03-19",
        "provider": "openai",
        "family": "o1",
        "status": "deprecated",
        "deprecated_at": "2026-04-22",
        "retired_at": "2026-10-23",
        "replacement_id": "gpt-5.6-sol",
        "aliases": ["o1-pro"],
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Replacement cell verbatim: 'gpt-5.6-sol (reasoning.mode: pro)'.",
    },
    {
        "id": "o3-mini-2025-01-31",
        "provider": "openai",
        "family": "o3",
        "status": "deprecated",
        "deprecated_at": "2026-04-22",
        "retired_at": "2026-10-23",
        "replacement_id": "gpt-5.6-sol",
        "aliases": ["o3-mini"],
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Section '2026-04-22: Legacy GPT model snapshots'.",
    },
    {
        "id": "o4-mini-2025-04-16",
        "provider": "openai",
        "family": "o4",
        "status": "deprecated",
        "deprecated_at": "2026-04-22",
        "retired_at": "2026-10-23",
        "replacement_id": "gpt-5.6-terra",
        "aliases": ["o4-mini"],
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Section '2026-04-22: Legacy GPT model snapshots'. Model page "
        "https://developers.openai.com/api/docs/models/o4-mini (fetched 2026-09-18) says "
        "'succeeded by GPT-5 Mini'; the deprecations page names gpt-5.6-terra, which is "
        "carried.",
    },
    {
        "id": "gpt-image-1-mini",
        "provider": "openai",
        "family": "gpt-image",
        "status": "deprecated",
        "deprecated_at": "2026-06-02",
        "retired_at": "2026-12-01",
        "replacement_id": "gpt-image-2",
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Section '2026-06-02: GPT Image model deprecations': 'On June 2, 2026, we notified "
        "developers using older GPT Image models of their deprecation and removal from the "
        "API on December 1, 2026.' An image model.",
        "modality": "image",
    },
    {
        "id": "gpt-image-1.5",
        "provider": "openai",
        "family": "gpt-image",
        "status": "deprecated",
        "deprecated_at": "2026-06-02",
        "retired_at": "2026-12-01",
        "replacement_id": "gpt-image-2",
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Section '2026-06-02: GPT Image model deprecations'. An image model.",
        "modality": "image",
    },
    {
        "id": "chatgpt-image-latest",
        "provider": "openai",
        "family": "gpt-image",
        "status": "deprecated",
        "deprecated_at": "2026-06-02",
        "retired_at": "2026-12-01",
        "replacement_id": "gpt-image-2",
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Section '2026-06-02: GPT Image model deprecations'. An image model.",
        "modality": "image",
    },
    {
        "id": "gpt-5-2025-08-07",
        "provider": "openai",
        "family": "gpt-5",
        "status": "deprecated",
        "deprecated_at": "2026-06-11",
        "retired_at": "2026-12-11",
        "replacement_id": "gpt-5.6-sol",
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Section '2026-06-11: GPT-5 and o3 model deprecations': 'On June 11, 2026, we "
        "notified developers using older GPT-5 and o3 model snapshots of their deprecation "
        "and removal from the API on December 11, 2026.' Alias per "
        "https://developers.openai.com/api/docs/models/gpt-5 (fetched 2026-09-18), which "
        "also says 'We recommend using the latest GPT-6 Astra'.",
        "aliases": ["gpt-5"],
    },
    {
        "id": "gpt-5-mini-2025-08-07",
        "provider": "openai",
        "family": "gpt-5",
        "status": "deprecated",
        "deprecated_at": "2026-06-11",
        "retired_at": "2026-12-11",
        "replacement_id": "gpt-5.6-terra",
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Section '2026-06-11: GPT-5 and o3 model deprecations'. Alias per "
        "https://developers.openai.com/api/docs/models/gpt-5-mini (fetched 2026-09-18).",
        "aliases": ["gpt-5-mini"],
    },
    {
        "id": "gpt-5-nano-2025-08-07",
        "provider": "openai",
        "family": "gpt-5",
        "status": "deprecated",
        "deprecated_at": "2026-06-11",
        "retired_at": "2026-12-11",
        "replacement_id": "gpt-5.6-luna",
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Section '2026-06-11: GPT-5 and o3 model deprecations'. Alias per "
        "https://developers.openai.com/api/docs/models/gpt-5-nano (fetched 2026-09-18).",
        "aliases": ["gpt-5-nano"],
    },
    {
        "id": "gpt-5-pro-2025-10-06",
        "provider": "openai",
        "family": "gpt-5",
        "status": "deprecated",
        "deprecated_at": "2026-06-11",
        "retired_at": "2026-12-11",
        "replacement_id": "gpt-5.6-sol",
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Replacement cell verbatim: 'gpt-5.6-sol (reasoning.mode: pro)'. Alias per "
        "https://developers.openai.com/api/docs/models/gpt-5-pro (fetched 2026-09-18).",
        "aliases": ["gpt-5-pro"],
    },
    {
        "id": "o3-2025-04-16",
        "provider": "openai",
        "family": "o3",
        "status": "deprecated",
        "deprecated_at": "2026-06-11",
        "retired_at": "2026-12-11",
        "replacement_id": "gpt-5.6-sol",
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Section '2026-06-11: GPT-5 and o3 model deprecations'. Alias per "
        "https://developers.openai.com/api/docs/models/o3 (fetched 2026-09-18), which says "
        "'o3 is succeeded by GPT-5'.",
        "aliases": ["o3"],
    },
    {
        "id": "o3-pro-2025-06-10",
        "provider": "openai",
        "family": "o3",
        "status": "deprecated",
        "deprecated_at": "2026-06-11",
        "retired_at": "2026-12-11",
        "replacement_id": "gpt-5.6-sol",
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Replacement cell verbatim: 'gpt-5.6-sol (reasoning.mode: pro)'. Alias per "
        "https://developers.openai.com/api/docs/models/o3-pro (fetched 2026-09-18).",
        "aliases": ["o3-pro"],
    },
    {
        "id": "gpt-5.6-sol",
        "provider": "openai",
        "family": "gpt-5.6",
        "status": "active",
        "source_url": "https://developers.openai.com/api/docs/models/gpt-5.6-sol",
        "fetched_at": "2026-09-17",
        "notes": "Named as the recommended replacement for the 2026-10-23 and 2026-12-11 "
        "retirements. Model page endpoint table: Chat Completions supported, Responses "
        "supported; 'Reasoning.effort supports: none, low, medium (default), high, xhigh, "
        "and max.' Alias per the model page (fetched 2026-09-18): 'The gpt-5.6 alias routes "
        "requests to GPT-5.6 Sol.'",
        "aliases": ["gpt-5.6"],
    },
    {
        "id": "gpt-5.6-terra",
        "provider": "openai",
        "family": "gpt-5.6",
        "status": "active",
        "source_url": "https://developers.openai.com/api/docs/models/gpt-5.6-terra",
        "fetched_at": "2026-09-17",
        "notes": "Named as the recommended replacement for gpt-3.5-turbo-0125, o4-mini-2025-04-16 "
        "and gpt-5-mini-2025-08-07. Model page: Chat Completions supported, "
        "function_calling listed under supported features.",
    },
    {
        "id": "gpt-5.6-luna",
        "provider": "openai",
        "family": "gpt-5.6",
        "status": "active",
        "source_url": "https://developers.openai.com/api/docs/models/gpt-5.6-luna",
        "fetched_at": "2026-09-17",
        "notes": "Named as the recommended replacement for gpt-4.1-nano and gpt-5-nano-2025-08-07. "
        "Model page: 'Prompts with >272K input tokens are priced at 2x input and 1.5x "
        "output for the full request.'",
    },
    {
        "id": "gpt-5.6-cyber",
        "provider": "openai",
        "family": "gpt-5.6",
        "status": "active",
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Named as the replacement for gpt-5.4-cyber on the deprecations page; its own model "
        "page was not fetched.",
    },
    {
        "id": "gpt-image-2",
        "provider": "openai",
        "family": "gpt-image",
        "status": "active",
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Named as the replacement for every GPT Image retirement on the deprecations page; "
        "its own model page was not fetched. An image model.",
        "modality": "image",
    },
    {
        "id": "claude-opus-4-1-20250805",
        "provider": "anthropic",
        "family": "claude-opus-4",
        "status": "retired",
        "deprecated_at": "2026-06-05",
        "retired_at": "2026-08-05",
        "replacement_id": "claude-opus-4-8",
        "source_url": "https://platform.claude.com/docs/en/about-claude/model-deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Section '2026-06-05: Claude Opus 4.1 model'; note on the page: 'This model was "
        "retired August 5, 2026.'",
    },
    {
        "id": "claude-sonnet-4-20250514",
        "provider": "anthropic",
        "family": "claude-sonnet-4",
        "status": "retired",
        "deprecated_at": "2026-04-14",
        "retired_at": "2026-06-15",
        "replacement_id": "claude-sonnet-4-6",
        "source_url": "https://platform.claude.com/docs/en/about-claude/model-deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Section '2026-04-14: Claude Sonnet 4 and Claude Opus 4 models'; 'These models were "
        "retired June 15, 2026.'",
    },
    {
        "id": "claude-opus-4-20250514",
        "provider": "anthropic",
        "family": "claude-opus-4",
        "status": "retired",
        "deprecated_at": "2026-04-14",
        "retired_at": "2026-06-15",
        "replacement_id": "claude-opus-4-8",
        "source_url": "https://platform.claude.com/docs/en/about-claude/model-deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Section '2026-04-14: Claude Sonnet 4 and Claude Opus 4 models'; 'These models were "
        "retired June 15, 2026.'",
    },
    {
        "id": "claude-opus-4-8",
        "provider": "anthropic",
        "family": "claude-opus-4",
        "status": "active",
        "source_url": "https://platform.claude.com/docs/en/about-claude/model-deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Model status table: Active; tentative retirement 'Not sooner than May 28, 2027'. A "
        "floor the vendor publishes, not an announced date. Per the model-ids page (fetched "
        "2026-09-18) a 4.6-generation id is not an alias: it is the snapshot. Listed under "
        "'Legacy models (still available)'.",
        "aliases": [],
    },
    {
        "id": "claude-opus-4-7",
        "provider": "anthropic",
        "family": "claude-opus-4",
        "status": "active",
        "source_url": "https://platform.claude.com/docs/en/about-claude/model-deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Model status table: Active; tentative retirement 'Not sooner than April 16, 2027'. "
        "Per the model-ids page (fetched 2026-09-18) a 4.6-generation id is not an alias: "
        "it is the snapshot. Listed under 'Legacy models (still available)'.",
        "aliases": [],
    },
    {
        "id": "claude-opus-4-6",
        "provider": "anthropic",
        "family": "claude-opus-4",
        "status": "active",
        "source_url": "https://platform.claude.com/docs/en/about-claude/model-deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Model status table: Active; tentative retirement 'Not sooner than February 5, "
        "2027'. Per the model-ids page (fetched 2026-09-18) a 4.6-generation id is not an "
        "alias: it is the snapshot. Listed under 'Legacy models (still available)'.",
        "aliases": [],
    },
    {
        "id": "claude-opus-4-5-20251101",
        "provider": "anthropic",
        "family": "claude-opus-4",
        "status": "active",
        "source_url": "https://platform.claude.com/docs/en/about-claude/model-deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Model status table: Active; tentative retirement 'Not sooner than November 24, "
        "2026'. Alias per https://platform.claude.com/docs/en/models/opus-4-5/overview "
        "(fetched 2026-09-18); listed under 'Legacy models (still available)'.",
        "aliases": ["claude-opus-4-5"],
    },
    {
        "id": "claude-sonnet-4-6",
        "provider": "anthropic",
        "family": "claude-sonnet-4",
        "status": "active",
        "source_url": "https://platform.claude.com/docs/en/about-claude/model-deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Model status table: Active; tentative retirement 'Not sooner than February 17, "
        "2027'. Per the model-ids page (fetched 2026-09-18) a 4.6-generation id is not an "
        "alias: it is the snapshot. Listed under 'Legacy models (still available)'.",
        "aliases": [],
    },
    {
        "id": "claude-sonnet-4-5-20250929",
        "provider": "anthropic",
        "family": "claude-sonnet-4",
        "status": "active",
        "source_url": "https://platform.claude.com/docs/en/about-claude/model-deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Model status table: Active; tentative retirement 'Not sooner than September 29, "
        "2026'. The vendor's policy is at least 60 days' notice before retirement. Alias "
        "per https://platform.claude.com/docs/en/models/sonnet-4-5/overview (fetched "
        "2026-09-18); the overview lists it under 'Legacy models (still available)'.",
        "aliases": ["claude-sonnet-4-5"],
    },
    {
        "id": "claude-haiku-4-5",
        "provider": "anthropic",
        "family": "claude-haiku-4",
        "status": "active",
        "aliases": ["claude-haiku-4-5-20251001"],
        "source_url": "https://platform.claude.com/docs/en/about-claude/model-deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Model status table row 'claude-haiku-4-5-20251001': Active; tentative retirement "
        "'Not sooner than October 15, 2026'. The vendor's policy is at least 60 days' "
        "notice before retirement. The haiku page (fetched 2026-09-18): 'claude-haiku-4-5 "
        "is a convenience alias that resolves to the pinned snapshot "
        "claude-haiku-4-5-20251001'; status 'Active (latest)'.",
    },
    {
        "id": "gemini-omni-flash-preview",
        "provider": "google",
        "family": "gemini-omni",
        "status": "deprecated",
        "retired_at": "2026-09-30",
        "replacement_id": "gemini-omni-1.1-flash",
        "source_url": "https://ai.google.dev/gemini-api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Gemini API deprecations table; release date June 30, 2026. Page: 'The shutdown "
        "dates listed in the table indicate the earliest possible dates on which a model "
        "might be retired.' No row on the Vertex AI lifecycle page.",
    },
    {
        "id": "gemini-2.5-flash-image",
        "provider": "google",
        "family": "gemini-2.5",
        "status": "deprecated",
        "retired_at": "2026-10-02",
        "source_url": "https://ai.google.dev/gemini-api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Gemini API shutdown October 2, 2026, replacement cell "
        "gemini-3.1-flash-image-preview, which the same page lists with shutdown June 25, "
        "2026. Vertex AI retires this id March 15, 2027 with replacement 'Gemini 3.1 "
        "Flash-Lite Image' (gemini-3.1-flash-lite-image). No single successor is safe to "
        "name. An image model.",
        "modality": "image",
    },
    {
        "id": "gemini-2.5-pro",
        "provider": "google",
        "family": "gemini-2.5",
        "status": "deprecated",
        "retired_at": "2026-10-20",
        "replacement_id": "gemini-3.5-flash",
        "source_url": "https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/model-versions",
        "fetched_at": "2026-09-17",
        "notes": "Vertex AI lifecycle table: October 20, 2026, replacement 'Gemini 3.5 Flash' (id "
        "from https://ai.google.dev/gemini-api/docs/models). The Vertex release note of "
        "2026-04-02 said October 16, 2026 "
        "(https://docs.cloud.google.com/vertex-ai/generative-ai/docs/release-notes); the "
        "lifecycle table is carried. Gemini API page: 'No shutdown date announced'. Vertex "
        "policy: 'While retirement timelines may be extended, they won't be moved to an "
        "earlier date than what is listed.'",
    },
    {
        "id": "gemini-2.5-flash",
        "provider": "google",
        "family": "gemini-2.5",
        "status": "deprecated",
        "retired_at": "2026-10-20",
        "replacement_id": "gemini-3.5-flash-lite",
        "source_url": "https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/model-versions",
        "fetched_at": "2026-09-17",
        "notes": "Vertex AI lifecycle table: October 20, 2026, replacement 'Gemini 3.5 Flash-Lite or "
        "Gemini 3.1 Flash-Lite' (ids gemini-3.5-flash-lite, gemini-3.1-flash-lite). The "
        "Vertex release note of 2026-04-02 said October 16, 2026; the lifecycle table is "
        "carried. Gemini API page: 'No shutdown date announced'.",
    },
    {
        "id": "gemini-2.5-flash-lite",
        "provider": "google",
        "family": "gemini-2.5",
        "status": "deprecated",
        "retired_at": "2026-10-20",
        "replacement_id": "gemini-3.1-flash-lite",
        "source_url": "https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/model-versions",
        "fetched_at": "2026-09-17",
        "notes": "Vertex AI lifecycle table: October 20, 2026, replacement 'Gemini 3.1 Flash-Lite or "
        "Gemma 4' (id gemini-3.1-flash-lite from "
        "https://ai.google.dev/gemini-api/docs/models; the Gemma 4 id on Vertex is "
        "gemma-4-26b-a4b-it-maas). The Vertex release note of 2026-04-02 said October 16, "
        "2026; the lifecycle table is carried. Gemini API page: 'No shutdown date "
        "announced'.",
    },
    {
        "id": "gemini-live-2.5-flash-native-audio",
        "provider": "google",
        "family": "gemini-2.5",
        "status": "deprecated",
        "retired_at": "2026-12-13",
        "source_url": "https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/model-versions",
        "fetched_at": "2026-09-17",
        "notes": "Vertex AI lifecycle table: December 13, 2026; replacement cell blank; release date "
        "December 12, 2025. The Gemini API page has no row with this id. A live audio "
        "model.",
        "modality": "audio",
    },
    {
        "id": "gemini-3.8-flash",
        "provider": "google",
        "family": "gemini-3.8",
        "status": "active",
        "source_url": "https://ai.google.dev/gemini-api/docs/models",
        "fetched_at": "2026-09-17",
        "notes": "Gemini API models page: 'New' and 'Stable' badges. Vertex AI lists it under "
        "'Models available for shorter availability periods' ('Short-term availability "
        "models retire 45 days after a replacement model is released'), released September "
        "2, 2026, 'No retirement date announced'.",
    },
    {
        "id": "gemini-3.7-flash",
        "provider": "google",
        "family": "gemini-3.7",
        "status": "active",
        "source_url": "https://ai.google.dev/gemini-api/docs/models",
        "fetched_at": "2026-09-17",
        "notes": "Gemini API models page: 'Stable'. Vertex AI lists it under 'Models available for "
        "shorter availability periods' ('Short-term availability models retire 45 days "
        "after a replacement model is released'), released August 13, 2026, 'No retirement "
        "date announced'.",
    },
    {
        "id": "gemini-3.6-flash",
        "provider": "google",
        "family": "gemini-3.6",
        "status": "active",
        "source_url": "https://ai.google.dev/gemini-api/docs/models",
        "fetched_at": "2026-09-17",
        "notes": "Gemini API models page: 'Stable'. Vertex AI lists it under 'Models available for "
        "shorter availability periods' ('Short-term availability models retire 45 days "
        "after a replacement model is released'), released July 21, 2026, 'No retirement "
        "date announced'.",
    },
    {
        "id": "gemini-3.5-flash",
        "provider": "google",
        "family": "gemini-3.5",
        "status": "active",
        "source_url": "https://ai.google.dev/gemini-api/docs/models",
        "fetched_at": "2026-09-17",
        "notes": "Gemini API models page: 'Stable'. Vertex AI lifecycle table "
        "(https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/model-versions): "
        "released May 19, 2026, retirement date 'May 19, 2027 or later'. Named on that "
        "table as the replacement for gemini-2.5-pro.",
    },
    {
        "id": "gemini-3.5-flash-lite",
        "provider": "google",
        "family": "gemini-3.5",
        "status": "active",
        "source_url": "https://ai.google.dev/gemini-api/docs/models",
        "fetched_at": "2026-09-17",
        "notes": "Gemini API models page: 'Stable'. Vertex AI lifecycle table "
        "(https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/model-versions): "
        "released July 21, 2026, retirement date 'July 21, 2027 or later'. Named on that "
        "table as a replacement for gemini-2.5-flash, and on the Gemini API deprecations "
        "page as the replacement for gemini-3.1-flash-lite.",
    },
    {
        "id": "gemini-3.1-flash-lite",
        "provider": "google",
        "family": "gemini-3.1",
        "status": "active",
        "source_url": "https://ai.google.dev/gemini-api/docs/deprecations",
        "fetched_at": "2026-09-18",
        "notes": "Gemini API deprecations table: released May 7, 2026, shutdown May 7, 2027 ('the "
        "earliest possible dates on which a model might be retired'), replacement "
        "gemini-3.5-flash-lite. Vertex AI lifecycle table "
        "(https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/model-versions): "
        "'May 7, 2027 or later'. Gemini API models page: 'Stable'. Named on the Vertex "
        "table as a replacement for gemini-2.5-flash and gemini-2.5-flash-lite.",
        "retired_at": "2027-05-07",
        "replacement_id": "gemini-3.5-flash-lite",
    },
    {
        "id": "gemini-3.1-flash-lite-image",
        "provider": "google",
        "family": "gemini-3.1",
        "status": "active",
        "source_url": "https://ai.google.dev/gemini-api/docs/models",
        "fetched_at": "2026-09-17",
        "notes": "Gemini API models page: 'Stable', display name 'Nano Banana 2 Lite'. Vertex AI "
        "lifecycle table "
        "(https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/model-versions): "
        "released June 23, 2026, retirement date 'June 28, 2027 or later'. An image model.",
        "modality": "image",
    },
    {
        "id": "gemini-omni-1.1-flash",
        "provider": "google",
        "family": "gemini-omni",
        "status": "active",
        "source_url": "https://ai.google.dev/gemini-api/docs/models",
        "fetched_at": "2026-09-17",
        "notes": "Gemini API models page: 'New'. Named on "
        "https://ai.google.dev/gemini-api/docs/deprecations as the replacement for "
        "gemini-omni-flash-preview.",
    },
    {
        "id": "gpt-4o-2024-08-06",
        "provider": "openai",
        "family": "gpt-4o",
        "status": "active",
        "aliases": ["gpt-4o"],
        "source_url": "https://developers.openai.com/api/docs/models/gpt-4o",
        "fetched_at": "2026-09-18",
        "notes": "Model page: default snapshot for the gpt-4o alias. Not named on the deprecations "
        "page as of 2026-09-18.",
    },
    {
        "id": "gpt-4o-2024-11-20",
        "provider": "openai",
        "family": "gpt-4o",
        "status": "active",
        "source_url": "https://developers.openai.com/api/docs/models/gpt-4o-2024-11-20",
        "fetched_at": "2026-09-18",
        "notes": "Model page. Not named on the deprecations page as of 2026-09-18.",
    },
    {
        "id": "gpt-4o-mini-2024-07-18",
        "provider": "openai",
        "family": "gpt-4o-mini",
        "status": "active",
        "aliases": ["gpt-4o-mini"],
        "source_url": "https://developers.openai.com/api/docs/models/gpt-4o-mini",
        "fetched_at": "2026-09-18",
        "notes": "Model page: default snapshot for the gpt-4o-mini alias. Not named on the "
        "deprecations page as of 2026-09-18.",
    },
    {
        "id": "gpt-4.1-2025-04-14",
        "provider": "openai",
        "family": "gpt-4.1",
        "status": "active",
        "aliases": ["gpt-4.1"],
        "source_url": "https://developers.openai.com/api/docs/models/gpt-4.1",
        "fetched_at": "2026-09-18",
        "notes": "Model page: default snapshot for the gpt-4.1 alias. Not named on the deprecations "
        "page as of 2026-09-18.",
    },
    {
        "id": "gpt-4.1-mini-2025-04-14",
        "provider": "openai",
        "family": "gpt-4.1",
        "status": "active",
        "aliases": ["gpt-4.1-mini"],
        "source_url": "https://developers.openai.com/api/docs/models/gpt-4.1-mini",
        "fetched_at": "2026-09-18",
        "notes": "Model page: default snapshot for the gpt-4.1-mini alias. Not named on the "
        "deprecations page as of 2026-09-18.",
    },
    {
        "id": "gpt-5.1-2025-11-13",
        "provider": "openai",
        "family": "gpt-5.1",
        "status": "active",
        "aliases": ["gpt-5.1"],
        "source_url": "https://developers.openai.com/api/docs/models/gpt-5.1",
        "fetched_at": "2026-09-18",
        "notes": "Model page: default snapshot for the gpt-5.1 alias. Not named on the deprecations "
        "page as of 2026-09-18.",
    },
    {
        "id": "gpt-5.2-2025-12-11",
        "provider": "openai",
        "family": "gpt-5.2",
        "status": "active",
        "aliases": ["gpt-5.2"],
        "source_url": "https://developers.openai.com/api/docs/models/gpt-5.2",
        "fetched_at": "2026-09-18",
        "notes": "Model page: default snapshot for the gpt-5.2 alias. Not named on the deprecations "
        "page as of 2026-09-18. Model page wording: 'previous flagship model ... We "
        "recommend using the latest GPT-6 Astra'.",
    },
    {
        "id": "gpt-5.2-pro-2025-12-11",
        "provider": "openai",
        "family": "gpt-5.2",
        "status": "active",
        "aliases": ["gpt-5.2-pro"],
        "source_url": "https://developers.openai.com/api/docs/models/gpt-5.2-pro",
        "fetched_at": "2026-09-18",
        "notes": "Model page: default snapshot for the gpt-5.2-pro alias. Not named on the "
        "deprecations page as of 2026-09-18. Model page wording: 'previous pro model ... "
        "GPT-5.5 Pro for the latest pro model'.",
    },
    {
        "id": "gpt-5.4-2026-03-05",
        "provider": "openai",
        "family": "gpt-5.4",
        "status": "active",
        "aliases": ["gpt-5.4"],
        "source_url": "https://developers.openai.com/api/docs/models/gpt-5.4",
        "fetched_at": "2026-09-18",
        "notes": "Model page: default snapshot for the gpt-5.4 alias. Not named on the deprecations "
        "page as of 2026-09-18.",
    },
    {
        "id": "gpt-5.4-mini-2026-03-17",
        "provider": "openai",
        "family": "gpt-5.4",
        "status": "active",
        "aliases": ["gpt-5.4-mini"],
        "source_url": "https://developers.openai.com/api/docs/models/gpt-5.4-mini",
        "fetched_at": "2026-09-18",
        "notes": "Model page: default snapshot for the gpt-5.4-mini alias. Not named on the "
        "deprecations page as of 2026-09-18.",
    },
    {
        "id": "gpt-5.4-nano-2026-03-17",
        "provider": "openai",
        "family": "gpt-5.4",
        "status": "active",
        "aliases": ["gpt-5.4-nano"],
        "source_url": "https://developers.openai.com/api/docs/models/gpt-5.4-nano",
        "fetched_at": "2026-09-18",
        "notes": "Model page: default snapshot for the gpt-5.4-nano alias. Not named on the "
        "deprecations page as of 2026-09-18.",
    },
    {
        "id": "gpt-5.4-pro-2026-03-05",
        "provider": "openai",
        "family": "gpt-5.4",
        "status": "active",
        "aliases": ["gpt-5.4-pro"],
        "source_url": "https://developers.openai.com/api/docs/models/gpt-5.4-pro",
        "fetched_at": "2026-09-18",
        "notes": "Model page: default snapshot for the gpt-5.4-pro alias. Not named on the "
        "deprecations page as of 2026-09-18.",
    },
    {
        "id": "gpt-5.5-2026-04-23",
        "provider": "openai",
        "family": "gpt-5.5",
        "status": "active",
        "aliases": ["gpt-5.5"],
        "source_url": "https://developers.openai.com/api/docs/models/gpt-5.5",
        "fetched_at": "2026-09-18",
        "notes": "Model page: default snapshot for the gpt-5.5 alias. Not named on the deprecations "
        "page as of 2026-09-18.",
    },
    {
        "id": "gpt-5.5-pro-2026-04-23",
        "provider": "openai",
        "family": "gpt-5.5",
        "status": "active",
        "aliases": ["gpt-5.5-pro"],
        "source_url": "https://developers.openai.com/api/docs/models/gpt-5.5-pro",
        "fetched_at": "2026-09-18",
        "notes": "Model page: default snapshot for the gpt-5.5-pro alias. Not named on the "
        "deprecations page as of 2026-09-18.",
    },
    {
        "id": "gpt-6-astra",
        "provider": "openai",
        "family": "gpt-6",
        "status": "active",
        "source_url": "https://developers.openai.com/api/docs/models/gpt-6-astra",
        "fetched_at": "2026-09-18",
        "notes": "Model page. Not named on the deprecations page as of 2026-09-18. Model page "
        "wording: 'Our most capable model, built for the hardest end-to-end work'; the "
        "dateless id is its own default snapshot.",
    },
    {
        "id": "o1-mini-2024-09-12",
        "provider": "openai",
        "family": "o1",
        "status": "retired",
        "deprecated_at": "2025-04-28",
        "retired_at": "2025-10-27",
        "aliases": ["o1-mini"],
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-18",
        "notes": "Deprecations page entry 2025-04-28, shutdown October 27, 2025. The model page "
        "(https://developers.openai.com/api/docs/models/o1-mini) says 'we recommend using "
        "the newer o3-mini model', itself retiring 2026-10-23; no replacement is carried.",
    },
    {
        "id": "chatgpt-4o-latest",
        "provider": "openai",
        "family": "chatgpt-4o",
        "status": "retired",
        "deprecated_at": "2025-11-18",
        "retired_at": "2026-02-17",
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-18",
        "notes": "Deprecations page entry 2025-11-18, shutdown February 17, 2026. Model page "
        "(https://developers.openai.com/api/docs/models/chatgpt-4o-latest): 'has been "
        "deprecated and removed from the API'.",
    },
    {
        "id": "gpt-5-chat-latest",
        "provider": "openai",
        "family": "gpt-5",
        "status": "retired",
        "deprecated_at": "2026-04-22",
        "retired_at": "2026-07-23",
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-18",
        "notes": "Deprecations page entry 2026-04-22, shutdown July 23, 2026. The model page still "
        "serves and names no snapshot.",
    },
    {
        "id": "gpt-5.1-chat-latest",
        "provider": "openai",
        "family": "gpt-5.1",
        "status": "retired",
        "deprecated_at": "2026-04-22",
        "retired_at": "2026-07-23",
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-18",
        "notes": "Deprecations page entry 2026-04-22, shutdown July 23, 2026. Model page: 'We "
        "recommend GPT-6 Astra for most API usage'.",
    },
    {
        "id": "gpt-5.2-chat-latest",
        "provider": "openai",
        "family": "gpt-5.2",
        "status": "retired",
        "deprecated_at": "2026-05-08",
        "retired_at": "2026-08-10",
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-18",
        "notes": "Deprecations page entry 2026-05-08, shutdown August 10, 2026. Model page: 'This "
        "model has been deprecated. We recommend GPT-6 Astra for most API usage.'",
    },
    {
        "id": "gpt-5.3-chat-latest",
        "provider": "openai",
        "family": "gpt-5.3",
        "status": "retired",
        "deprecated_at": "2026-05-08",
        "retired_at": "2026-08-10",
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-18",
        "notes": "Deprecations page entry 2026-05-08, shutdown August 10, 2026. Model page: 'This "
        "model has been deprecated. We recommend GPT-6 Astra for most API usage.'",
    },
    {
        "id": "claude-fable-5-1",
        "provider": "anthropic",
        "family": "claude-fable-5",
        "status": "active",
        "source_url": "https://platform.claude.com/docs/en/models/overview",
        "fetched_at": "2026-09-18",
        "notes": "Overview page: a dateless id is its own pinned snapshot ('Dateless IDs are their "
        "own pinned snapshot; the alias row repeats them'). Deprecations page status: "
        "Active.",
    },
    {
        "id": "claude-opus-5",
        "provider": "anthropic",
        "family": "claude-opus-5",
        "status": "active",
        "source_url": "https://platform.claude.com/docs/en/models/overview",
        "fetched_at": "2026-09-18",
        "notes": "Overview page: a dateless id is its own pinned snapshot ('Dateless IDs are their "
        "own pinned snapshot; the alias row repeats them'). Deprecations page status: "
        "Active.",
    },
    {
        "id": "claude-sonnet-5",
        "provider": "anthropic",
        "family": "claude-sonnet-5",
        "status": "active",
        "source_url": "https://platform.claude.com/docs/en/models/overview",
        "fetched_at": "2026-09-18",
        "notes": "Overview page: a dateless id is its own pinned snapshot ('Dateless IDs are their "
        "own pinned snapshot; the alias row repeats them'). Deprecations page status: "
        "Active.",
    },
    {
        "id": "claude-fable-5",
        "provider": "anthropic",
        "family": "claude-fable-5",
        "status": "active",
        "source_url": "https://platform.claude.com/docs/en/models/overview",
        "fetched_at": "2026-09-18",
        "notes": "Overview page: a dateless id is its own pinned snapshot ('Dateless IDs are their "
        "own pinned snapshot; the alias row repeats them'). Deprecations page status: "
        "Active. Listed under 'Legacy models (still available)'.",
    },
    {
        "id": "gpt-3.5-turbo-instruct",
        "provider": "openai",
        "family": "gpt-3.5",
        "status": "deprecated",
        "deprecated_at": "2025-09-26",
        "retired_at": "2026-09-28",
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-18",
        "notes": "Section '2025-09-26: Legacy GPT model snapshots' under Upcoming deprecations: "
        "shutdown September 28, 2026. The replacement cell was not transcribed; choose a "
        "successor and run the check yourself.",
    },
    {
        "id": "gpt-3.5-turbo-1106",
        "provider": "openai",
        "family": "gpt-3.5",
        "status": "deprecated",
        "deprecated_at": "2025-09-26",
        "retired_at": "2026-09-28",
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-18",
        "notes": "Section '2025-09-26: Legacy GPT model snapshots' under Upcoming deprecations: "
        "shutdown September 28, 2026. The replacement cell was not transcribed; choose a "
        "successor and run the check yourself.",
    },
    {
        "id": "babbage-002",
        "provider": "openai",
        "family": "babbage",
        "status": "deprecated",
        "deprecated_at": "2025-09-26",
        "retired_at": "2026-09-28",
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-18",
        "notes": "Section '2025-09-26: Legacy GPT model snapshots' under Upcoming deprecations: "
        "shutdown September 28, 2026. The replacement cell was not transcribed; choose a "
        "successor and run the check yourself.",
    },
    {
        "id": "davinci-002",
        "provider": "openai",
        "family": "davinci",
        "status": "deprecated",
        "deprecated_at": "2025-09-26",
        "retired_at": "2026-09-28",
        "source_url": "https://developers.openai.com/api/docs/deprecations",
        "fetched_at": "2026-09-18",
        "notes": "Section '2025-09-26: Legacy GPT model snapshots' under Upcoming deprecations: "
        "shutdown September 28, 2026. The replacement cell was not transcribed; choose a "
        "successor and run the check yourself.",
    },
    {
        "id": "gemini-2.0-flash",
        "provider": "google",
        "family": "gemini-2.0",
        "status": "retired",
        "retired_at": "2026-06-01",
        "source_url": "https://ai.google.dev/gemini-api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Gemini API deprecations table and the Vertex AI lifecycle table both give June 1, "
        "2026. No replacement transcribed.",
    },
    {
        "id": "gemini-2.0-flash-lite",
        "provider": "google",
        "family": "gemini-2.0",
        "status": "retired",
        "retired_at": "2026-06-01",
        "source_url": "https://ai.google.dev/gemini-api/docs/deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Gemini API deprecations table and the Vertex AI lifecycle table both give June 1, "
        "2026. No replacement transcribed.",
    },
    {
        "id": "claude-mythos-preview",
        "provider": "anthropic",
        "family": "claude-mythos",
        "status": "deprecated",
        "replacement_id": "claude-mythos-5",
        "source_url": "https://platform.claude.com/docs/en/about-claude/model-deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Page note: claude-mythos-preview 'is deprecated', with migration to "
        "claude-mythos-5; no deprecation or retirement date appears in any table on the "
        "page.",
    },
    {
        "id": "claude-mythos-5",
        "provider": "anthropic",
        "family": "claude-mythos",
        "status": "active",
        "source_url": "https://platform.claude.com/docs/en/about-claude/model-deprecations",
        "fetched_at": "2026-09-17",
        "notes": "Named on the deprecations page as the migration target for claude-mythos-preview; "
        "not listed on the models overview fetched 2026-09-18.",
    },
]
# --- END SEED ---
