"""Packaging contract: the wheel is CODE ONLY.

MP-01 / #28. `modelpin` 0.1.1 shipped `modelpin/**.py` and nothing else, while the README
quickstart read `examples/`, `watcher.load_registry()` read `data/models.json`, and
`mp report` defaulted to `examples/report-suite`. Every one of those failed on a clean
install, and the error told the user to run `mp init`, which did not help.

ADR-0011 resolved that by making the *program* self-sufficient rather than making the
*archive* bigger: nothing outside the package is read at runtime, the registry is embedded
in `watcher/registry.py`, and the demo is generated by `mp init --demo` into the user's own
directory. The invariant that keeps it true is deliberately CLOSED —

    the wheel contains zero non-.py entries outside dist-info

— rather than a list of assets someone must remember to extend. A new data file cannot be
added without this test noticing, whereas an enumerated `REQUIRED = [...]` silently permits
whatever nobody thought to enumerate.

Working from the source tree hides this whole defect class (an editable install resolves
`parents[2]` to the repo root, and `Path.cwd()` is the repo root when you run from it), so
this builds a wheel from a pristine copy of the tree and inspects the archive itself.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

import pytest

# Never copy secrets (.env.local holds real API keys) or build residue into the temp tree.
# `*.egg-info` is load-bearing, not hygiene: a stale egg-info makes setuptools ship files
# the current pyproject no longer selects, which produces a FALSE GREEN here.
_IGNORE = shutil.ignore_patterns(
    ".git",
    ".venv",
    ".env*",
    "build",
    "dist",
    "*.egg-info",
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".modelpin",
)

_BUILD_WHEEL = (
    "import sys; from setuptools import build_meta; "
    "sys.stdout.write(build_meta.build_wheel(sys.argv[1]))"
)

#: Modules whose absence would silently re-break a surface MP-01 fixed. Unlike a list of
#: data files, this cannot grow stale: each entry maps to a user-visible command.
_REQUIRED_MODULES = {
    "modelpin/demo.py": "`mp init --demo` cannot work",
    "modelpin/watcher/registry.py": "load_registry() is DOA on a clean install",
    "modelpin/cli.py": "there is no CLI",
}


def _repo_root() -> Path:
    """Nearest ancestor holding pyproject.toml (the repo root when this file lives in tests/)."""
    for parent in Path(__file__).resolve().parents:
        if (parent / "pyproject.toml").is_file():
            return parent
    raise RuntimeError(f"no pyproject.toml above {__file__}")


def wheel_contract_problems(names: list[str]) -> list[str]:
    """Every way a wheel's member list violates the code-only contract. Empty == compliant.

    Pure and side-effect free so the guard itself can be mutation-tested below — a check
    that cannot be shown to fail is not evidence of anything.
    """
    problems: list[str] = []
    top = sorted({n.split("/")[0] for n in names})
    info = next((t for t in top if t.endswith(".dist-info")), None)
    if info is None:
        return [f"no .dist-info in the archive; top-level was {top}"]

    if top != sorted(["modelpin", info]):
        problems.append(f"unexpected top-level entries: {top}")

    stowaways = sorted(n for n in names if not n.endswith(".py") and not n.startswith(info))
    if stowaways:
        problems.append(
            "non-.py files in the wheel (the wheel is code only, ADR-0011): " + ", ".join(stowaways)
        )

    for module, consequence in sorted(_REQUIRED_MODULES.items()):
        if not any(n == module for n in names):
            problems.append(f"{module} missing - {consequence}")
    return problems


@pytest.fixture(scope="module")
def wheel_entries(tmp_path_factory: pytest.TempPathFactory) -> list[str]:
    """Every archive member of a wheel built from the current tree.

    Built via the project's own PEP 517 backend (setuptools, already required by
    [build-system]) rather than the `build` package, so a missing dev tool can never be
    mistaken for the packaging defect under test.
    """
    tmp = tmp_path_factory.mktemp("mp01")
    src, out = tmp / "src", tmp / "out"
    shutil.copytree(_repo_root(), src, ignore=_IGNORE)
    out.mkdir()

    proc = subprocess.run(
        [sys.executable, "-c", _BUILD_WHEEL, str(out)],
        cwd=src,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        pytest.fail(
            f"wheel build failed (rc={proc.returncode}) -- this is a harness problem, "
            f"not the defect under test.\nstdout:\n{proc.stdout}\nstderr:\n{proc.stderr}"
        )

    wheels = sorted(out.glob("*.whl"))
    assert len(wheels) == 1, f"expected exactly one wheel, got {[w.name for w in wheels]}"
    with zipfile.ZipFile(wheels[0]) as zf:
        return zf.namelist()


def test_wheel_is_code_only(wheel_entries: list[str]) -> None:
    """The closed invariant. Adding any data file to the package trips this."""
    problems = wheel_contract_problems(wheel_entries)
    assert not problems, "wheel violates the code-only contract:\n  - " + "\n  - ".join(problems)


def test_wheel_ships_both_console_scripts(wheel_entries: list[str]) -> None:
    """`mp` and `modelpin` both come from [project.scripts]; losing one is silent."""
    entry_points = [n for n in wheel_entries if n.endswith(".dist-info/entry_points.txt")]
    assert entry_points, f"no entry_points.txt in the wheel: {sorted(wheel_entries)}"


@pytest.mark.parametrize(
    ("mutation", "expected_fragment"),
    [
        (["modelpin/demo.py"], "modelpin/demo.py missing"),
        (["modelpin/watcher/registry.py"], "modelpin/watcher/registry.py missing"),
    ],
)
def test_guard_detects_a_missing_module(
    wheel_entries: list[str], mutation: list[str], expected_fragment: str
) -> None:
    """Mutation test: remove a required module and the guard MUST go red.

    Without this, `test_wheel_is_code_only` passing proves only that it ran.
    """
    mutated = [n for n in wheel_entries if n not in mutation]
    problems = wheel_contract_problems(mutated)
    assert any(expected_fragment in p for p in problems), (
        f"guard stayed green after deleting {mutation} - it does not discriminate. "
        f"Problems reported: {problems}"
    )


def test_guard_detects_a_stowaway_data_file(wheel_entries: list[str]) -> None:
    """Mutation test in the other direction: smuggle a data file in, guard MUST go red."""
    problems = wheel_contract_problems([*wheel_entries, "modelpin/data/models.json"])
    assert any("non-.py files in the wheel" in p for p in problems), (
        f"guard accepted a smuggled data file - the code-only contract is decorative. "
        f"Problems reported: {problems}"
    )
