"""MP-236 -- `modelpin scan` counted Modelpin's OWN scaffold comments as the user's dependencies.

`[M] 2026-09-09`, found by a first-run audit of the published 0.3.0 and reproduced verbatim
in a directory holding one 1-file app plus a fresh `modelpin init`:

    $ modelpin scan .
            Models this repo depends on
    +-----------------------------------------+
    | model            | file          | line |
    |------------------+---------------+------|
    | gpt-4o-mini      | app.py        | 6    |
    | gpt-4o-mini      | modelpin.yaml | 3    |
    | gpt-4o-mini      | modelpin.yaml | 8    |
    | gpt-4o-mini      | modelpin.yaml | 12   |     <- our scaffold comment
    | gpt-5.5          | app.py        | 19   |
    | qwen/qwen3.8-27b | modelpin.yaml | 14   |     <- our scaffold comment
    +-----------------------------------------+
    3 distinct model(s).

Lines 12 and 14 are inside the comment `modelpin init` had just written explaining the
judge-model-collision rule, and `qwen/qwen3.8-27b` is an illustrative id in that comment
which exists nowhere in the user's app. **Half the rows, and a third of the headline count,
were the tool talking to itself** -- on the first command a stranger runs. That is MP-200's
class (our `.modelpin/` store reported back as the user's models) in the one file we write
into the user's repo by hand.

The same audit found the opposite failure in the same number: `DEFAULT_EXTS` held no
documentation extension, so a repo whose `README.md` says *"we use `claude-3-5-sonnet` as a
fallback"* reported nothing. The count was simultaneously noisy and blind -- a safe ceiling
for neither and a safe floor for neither.

What is NOT fixed here, deliberately: a comment in the USER's own files stays in the table.
`# TODO: evaluate gpt-5.5` is a model that repo has a relationship with, and the audit read
it as a true positive; a commented-out `MODEL = "gpt-4o"` is the same. Those rows are
labelled `context="comment"` instead, which is what lets `modelpin scan` print them in their own
group later -- rendering that group is the CLI's half of this row.
"""

from __future__ import annotations

from pathlib import Path

from typer.testing import CliRunner

from modelpin.cli import app
from modelpin.config import DEFAULT_CONFIG_FILE, load_config
from modelpin.detector import DOC_EXTS, _comment_cut, models_used, scan_repo

runner = CliRunner()

#: The audited app, verbatim in shape: one wired-up model, one named only in a TODO.
_APP = '''"""A tiny app that calls one model."""

MODEL = "gpt-4o-mini"


def ask(client, question):
    return client.chat.completions.create(model=MODEL, messages=[])


# TODO: evaluate gpt-5.5 when it is generally available
'''


def _scaffolded(tmp_path: Path) -> Path:
    """The reproduction's directory: one app, plus a REAL `modelpin init`.

    The scaffold is generated by invoking the command, never by copying its template into
    this file. A copy would pass forever while `modelpin init`'s wording drifted away from it --
    which is MP-03, the defect that has already bitten this repo once.
    """
    (tmp_path / "app.py").write_text(_APP, encoding="utf-8")
    result = runner.invoke(app, ["init", str(tmp_path)])
    assert result.exit_code == 0, result.output
    assert (tmp_path / DEFAULT_CONFIG_FILE).is_file(), result.output
    return tmp_path


# --- the defect ---------------------------------------------------------------------------


def test_mp_init_adds_no_model_the_users_app_does_not_have(tmp_path) -> None:
    """The headline. `modelpin init` must not change the answer to "what does this repo use?"."""
    root = _scaffolded(tmp_path)
    assert models_used(root) == {"gpt-4o-mini", "gpt-5.5"}, sorted(models_used(root))


def test_every_model_reported_from_our_config_is_one_that_config_declares(tmp_path) -> None:
    """Checked against the CONFIG PARSER, not against a copy of the suppression rule.

    `load_config` is the independent oracle here: it is what the rest of the CLI believes
    `modelpin.yaml` says. If `scan` reports a model out of that file which the parser does
    not see as declared, `scan` is reading our own prose.
    """
    root = _scaffolded(tmp_path)
    cfg = load_config(root / DEFAULT_CONFIG_FILE)
    declared = set(cfg.models) | ({cfg.judge_model} if cfg.judge_model else set())
    reported = {h["model"] for h in scan_repo(root) if h["file"] == DEFAULT_CONFIG_FILE}
    assert reported <= declared, sorted(reported - declared)


def test_a_commented_out_setting_in_our_config_is_not_a_dependency(tmp_path) -> None:
    """A hand-edited config, because users edit the file we generate.

    Commenting a setting out is how you turn it OFF, so a judge model behind a `#` is the
    opposite of a declaration -- and prose about a model is not one either.
    """
    (tmp_path / "app.py").write_text('M = "gpt-4o-mini"\n', encoding="utf-8")
    (tmp_path / DEFAULT_CONFIG_FILE).write_text(
        "# NOTE: we moved off claude-opus-4-6 in June; it was retired.\n"
        "models:\n"
        "  - gpt-4o-mini\n"
        "# judge_model: gemini-2.5-pro\n",
        encoding="utf-8",
    )
    assert models_used(tmp_path) == {"gpt-4o-mini"}, sorted(models_used(tmp_path))


def test_the_rule_is_scoped_to_our_own_config_file(tmp_path) -> None:
    """Anti-over-fire: the same YAML under any other name is the user's, comments included."""
    (tmp_path / "settings.yaml").write_text("# fallback: claude-opus-4-6\n", encoding="utf-8")
    assert models_used(tmp_path) == {"claude-opus-4-6"}


# --- what must SURVIVE the fix -------------------------------------------------------------


def test_a_model_named_only_in_the_users_own_comment_is_still_reported(tmp_path) -> None:
    """`# TODO: evaluate gpt-5.5` is a true positive, and suppressing comments would eat it.

    It is reported, and labelled -- the label is the whole reason suppression was not the
    answer.
    """
    root = _scaffolded(tmp_path)
    todo = [h for h in scan_repo(root) if h["model"] == "gpt-5.5"]
    assert [(h["file"], h["context"]) for h in todo] == [("app.py", "comment")], todo


def test_a_wired_up_model_is_labelled_code(tmp_path) -> None:
    root = _scaffolded(tmp_path)
    wired = [h for h in scan_repo(root) if h["file"] == "app.py" and h["model"] == "gpt-4o-mini"]
    assert [h["context"] for h in wired] == ["code"], wired


def test_an_active_config_value_is_code_even_with_a_comment_after_it(tmp_path) -> None:
    """The scaffold's own shape: `- gpt-4o-mini   # the model your app depends on`.

    The id is left of the `#`, so cutting the line at the marker must not take the value
    with it. This is the row the fix is most at risk of over-deleting.
    """
    root = _scaffolded(tmp_path)
    cfg_hits = [h for h in scan_repo(root) if h["file"] == DEFAULT_CONFIG_FILE]
    assert cfg_hits, "the config declares gpt-4o-mini; scan must still see it"
    assert {h["context"] for h in cfg_hits} == {"code"}, cfg_hits


# --- the blind half: documentation ---------------------------------------------------------


def test_a_model_named_only_in_the_readme_is_found(tmp_path) -> None:
    """`[M]` The audit's second finding: this scanned to `No model identifiers found.`, exit 0."""
    (tmp_path / "README.md").write_text(
        "# App\n\nWe use `claude-3-5-sonnet` as a fallback when the primary is rate-limited.\n",
        encoding="utf-8",
    )
    hits = scan_repo(tmp_path)
    assert [(h["model"], h["file"], h["context"]) for h in hits] == [
        ("claude-3-5-sonnet", "README.md", "comment")
    ], hits


def test_a_txt_file_is_still_not_scanned(tmp_path) -> None:
    """`.txt` is excluded on purpose: it is the extension of logs and scraped dumps, which
    is what MP-201's 28 fabricated ids were made of. Pinned so that adding it is a decision
    someone makes with evidence, not a tidy-up."""
    assert ".txt" not in DOC_EXTS
    (tmp_path / "scraped.txt").write_text("gpt-6-astra-its-latest-ai-model\n", encoding="utf-8")
    assert models_used(tmp_path) == set()


# --- the one-line lexer --------------------------------------------------------------------


def test_a_comment_marker_inside_a_string_does_not_cut_the_line(tmp_path) -> None:
    """Otherwise the fix would relabel wired-up code as prose -- and, in our own config,
    delete it."""
    line = 'SEP = "a # b"\nMODEL = "gpt-4o-mini"  # or gpt-5.5 later\n'
    (tmp_path / "app.py").write_text(line, encoding="utf-8")
    got = {(h["model"], h["context"]) for h in scan_repo(tmp_path)}
    assert got == {("gpt-4o-mini", "code"), ("gpt-5.5", "comment")}, got


def test_comment_cut_reports_the_end_of_a_line_that_has_no_comment() -> None:
    assert _comment_cut('M = "gpt-4o"', "#") == len('M = "gpt-4o"')
    assert _comment_cut("const M = 'gpt-4o';", "//") == len("const M = 'gpt-4o';")
    assert _comment_cut("# all prose", "#") == 0
