"""Modelpin CLI (Typer). Wires the pipeline end-to-end:

    mp scan      -> detector
    mp init      -> scaffold modelpin.yaml + scenarios/
    mp baseline  -> replay current model N times, persist traces
    mp check     -> replay a new model, diff vs baseline, print the PR-style report

Replays use the END USER's API key from the environment (BYO-key, spec section 9);
`--provider fake --fixtures <file>` runs the whole flow offline for demos/tests.
"""

from __future__ import annotations

from pathlib import Path
from typing import NoReturn, Optional

import typer
from rich.box import ASCII as ASCII_BOX
from rich.console import Console
from rich.table import Table

from modelpin import __version__
from modelpin.config import DEFAULT_PROVIDER, ConfigError, ModelpinConfig, load_config
from modelpin.detector import scan_repo
from modelpin.diff import diff_scenario
from modelpin.models import DiffVerdict, Scenario
from modelpin.providers import ProviderAdapter, ProviderError, get_adapter
from modelpin.providers.fake import FakeProvider
from modelpin.replay import replay
from modelpin.report import render_cli, render_pr_comment
from modelpin.scenarios import ScenarioError, load_scenarios
from modelpin.storage import STORE_DIRNAME, BaselineError, load_baseline, save_baseline

#: A behavioral diff compares run *distributions*; fewer than this can't form one.
MIN_RUNS = 2
#: Below this, the permutation test is underpowered — warn but proceed.
RECOMMENDED_RUNS = 5

app = typer.Typer(
    help="Modelpin - Dependabot for AI models. Know before the model breaks you.",
    no_args_is_help=True,
    add_completion=False,
    rich_markup_mode=None,  # plain Click help: ASCII-only, never crashes on cp1252
)
console = Console()

_SAMPLE_SCENARIO = """{
  "id": "greeting",
  "name": "Simple greeting",
  "kind": "single",
  "input": {"messages": [{"role": "user", "content": "Say hello in one short sentence."}]},
  "assertions": {"must_contain": ["hello"]}
}
"""

_SAMPLE_CONFIG = """# modelpin.yaml - generated by `mp init`. See docs/ for the full reference.
models:
  - gpt-4o-mini            # the model your app currently depends on (set yours)
scenarios_dir: scenarios
providers:
  - openai                 # uses YOUR OPENAI_API_KEY from the environment
runs: 5                    # N replays per scenario (>=5 gives the diff real power)
judge_model: gpt-4o-mini   # semantic LLM-judge (optional; extra calls). Remove to disable.
"""


def _fail(message: str) -> NoReturn:
    console.print(f"[red]error:[/] {message}")
    raise typer.Exit(code=1)


def _adapter(provider: str, fixtures: Optional[str]) -> ProviderAdapter:
    try:
        if provider == "fake":
            return FakeProvider.from_fixtures(fixtures) if fixtures else FakeProvider()
        return get_adapter(provider)
    except FileNotFoundError as exc:
        _fail(f"fixtures file not found: {exc}")
    except ValueError as exc:  # unknown provider
        _fail(str(exc))


def _unimplemented_msg(provider: str) -> str:
    return (
        f"the {provider!r} adapter isn't implemented yet. Try `--provider fake "
        "--fixtures <file>` to run offline, or pick `--provider openai`."
    )


def _preflight_or_fail(adapter: ProviderAdapter, provider: str) -> None:
    """Fail before any tokens are spent if the provider isn't ready (key/SDK)."""
    try:
        adapter.preflight()
    except ProviderError as exc:
        _fail(str(exc))


def _guard_replay(provider: str, fn):
    """Run a replay step, converting adapter failures into friendly CLI errors."""
    try:
        return fn()
    except NotImplementedError:
        _fail(_unimplemented_msg(provider))
    except ProviderError as exc:
        _fail(str(exc))


def _build_judge(provider: str, cfg: ModelpinConfig):
    """Construct + preflight the semantic LLM-judge if configured. Returns None when no
    judge_model is set or the run is offline (fake), so the diff stays purely structural."""
    if not cfg.judge_model or provider == "fake":
        return None
    try:
        from modelpin.judge import build_judge

        judge = build_judge(provider, cfg.judge_model)
        judge.preflight()
    except (ProviderError, ImportError) as exc:
        _fail(f"semantic judge ({cfg.judge_model!r}): {exc}")
    console.print(f"[dim]semantic judge: {cfg.judge_model}[/]")
    return judge


def _load_config_or_fail(config_path: str) -> ModelpinConfig:
    try:
        return load_config(config_path)
    except ConfigError as exc:
        _fail(str(exc))


def _load_scenarios_or_fail(scenarios_dir: str) -> list[Scenario]:
    try:
        scenarios = load_scenarios(scenarios_dir)
    except ScenarioError as exc:
        _fail(str(exc))
    if not scenarios:
        _fail(f"no scenarios in {scenarios_dir!r}. Run `mp init` first.")
    return scenarios


def _resolve_provider(provider: Optional[str], cfg: ModelpinConfig) -> str:
    return provider or (cfg.providers[0] if cfg.providers else DEFAULT_PROVIDER)


def _resolve_runs(runs: Optional[int], cfg: ModelpinConfig) -> int:
    n = cfg.runs if runs is None else runs  # an explicit --runs 0 must hit the floor, not coerce
    if n < MIN_RUNS:
        _fail(
            f"--runs must be >= {MIN_RUNS}: the diff compares run *distributions*, and "
            f"a single run can't form one (got {n})."
        )
    if n < RECOMMENDED_RUNS:
        console.print(
            f"[yellow]warning:[/] only {n} runs/scenario; {RECOMMENDED_RUNS}+ gives the "
            "statistical diff real power and a lower false-positive rate."
        )
    return n


@app.command()
def version() -> None:
    """Print the Modelpin version."""
    console.print(f"modelpin {__version__}")


@app.command()
def scan(path: str = typer.Argument(".", help="Repo root to scan.")) -> None:
    """Detect which AI models this repo depends on, and where."""
    hits = scan_repo(path)
    if not hits:
        console.print("No model identifiers found.")
        return
    table = Table("model", "file", "line", title="Models this repo depends on", box=ASCII_BOX)
    for h in sorted(hits, key=lambda x: (x["model"], x["file"], x["line"])):
        table.add_row(h["model"], h["file"], str(h["line"]))
    console.print(table)
    console.print(f"[dim]{len({h['model'] for h in hits})} distinct model(s).[/]")


@app.command()
def init(directory: str = typer.Argument(".", help="Repo to scaffold.")) -> None:
    """Create modelpin.yaml + scenarios/ in the current repo (never overwrites)."""
    root = Path(directory)
    cfg = root / "modelpin.yaml"
    scenarios_dir = root / "scenarios"
    created: list[str] = []
    if not cfg.exists():
        cfg.write_text(_SAMPLE_CONFIG, encoding="utf-8")
        created.append(str(cfg))
    scenarios_dir.mkdir(parents=True, exist_ok=True)
    if not any(scenarios_dir.glob("*.json")):
        (scenarios_dir / "greeting.json").write_text(_SAMPLE_SCENARIO, encoding="utf-8")
        created.append(str(scenarios_dir / "greeting.json"))
    if created:
        console.print("[green]Scaffolded:[/]")
        for c in created:
            console.print(f"  - {c}")
        console.print("\nNext: add scenarios, then run [bold]mp baseline[/].")
    else:
        console.print("Already initialised (modelpin.yaml + scenarios/ present).")


@app.command()
def baseline(
    model: Optional[str] = typer.Option(
        None, "--model", help="Model to baseline (default: config)."
    ),
    provider: Optional[str] = typer.Option(None, "--provider", help="openai | anthropic | fake."),
    fixtures: Optional[str] = typer.Option(
        None, "--fixtures", help="Canned traces for --provider fake."
    ),
    runs: Optional[int] = typer.Option(None, "--runs", help="Replays per scenario."),
    config_path: str = typer.Option("modelpin.yaml", "--config"),
    scenarios_dir: Optional[str] = typer.Option(None, "--scenarios-dir"),
    store_dir: str = typer.Option(STORE_DIRNAME, "--store-dir"),
) -> None:
    """Record current model behavior for your scenarios (N runs)."""
    cfg = _load_config_or_fail(config_path)
    scenarios = _load_scenarios_or_fail(scenarios_dir or cfg.scenarios_dir)
    from_model = model or (cfg.models[0] if cfg.models else None)
    if not from_model:
        _fail("no model to baseline. Pass --model or set `models:` in modelpin.yaml.")
    n = _resolve_runs(runs, cfg)
    prov = _resolve_provider(provider, cfg)
    adapter = _adapter(prov, fixtures)
    console.print(f"[dim]provider={prov} model={from_model} runs={n}[/]")
    _preflight_or_fail(adapter, prov)
    traces = _guard_replay(
        prov, lambda: {s.id: replay(s, from_model, adapter, runs=n) for s in scenarios}
    )
    path = save_baseline(traces, from_model, store_dir)
    console.print(
        f"[green]Baseline recorded[/] for [bold]{from_model}[/]: "
        f"{len(scenarios)} scenario(s) x{n} runs -> {path}"
    )


@app.command()
def check(
    to: str = typer.Option(..., "--to", help="The new model id to test against your baseline."),
    from_: Optional[str] = typer.Option(None, "--from", help="Baseline model (default: config)."),
    provider: Optional[str] = typer.Option(None, "--provider", help="openai | anthropic | fake."),
    fixtures: Optional[str] = typer.Option(
        None, "--fixtures", help="Canned traces for --provider fake."
    ),
    runs: Optional[int] = typer.Option(None, "--runs", help="Replays per scenario."),
    mode: str = typer.Option(
        "strict", "--match", help="Tool-call match mode: strict|unordered|subset|superset."
    ),
    config_path: str = typer.Option("modelpin.yaml", "--config"),
    scenarios_dir: Optional[str] = typer.Option(None, "--scenarios-dir"),
    store_dir: str = typer.Option(STORE_DIRNAME, "--store-dir"),
) -> None:
    """Replay scenarios on a new model and report behavioral regressions."""
    cfg = _load_config_or_fail(config_path)
    scenarios = _load_scenarios_or_fail(scenarios_dir or cfg.scenarios_dir)
    from_model = from_ or (cfg.models[0] if cfg.models else None)
    if not from_model:
        _fail("no baseline model. Pass --from or set `models:` in modelpin.yaml.")
    try:
        base = load_baseline(from_model, store_dir)
    except FileNotFoundError as e:
        _fail(str(e))
    except BaselineError as e:
        _fail(str(e))
    n = _resolve_runs(runs, cfg)
    prov = _resolve_provider(provider, cfg)
    adapter = _adapter(prov, fixtures)
    console.print(f"[dim]provider={prov} from={from_model} to={to} runs={n} match={mode}[/]")
    _preflight_or_fail(adapter, prov)
    judge = _build_judge(prov, cfg)

    results = []
    skipped: list[str] = []

    def _run_check() -> None:
        for s in scenarios:
            base_traces = base.get(s.id)
            if not base_traces:
                skipped.append(s.id)
                continue
            cand = replay(s, to, adapter, runs=n)
            results.append(
                diff_scenario(s.id, from_model, to, base_traces, cand, s, mode, judge=judge)
            )

    _guard_replay(prov, _run_check)

    if not results:
        _fail("nothing to compare. Record a baseline first with `mp baseline`.")

    console.print(render_cli(results, from_model, to, n))

    # Decide the CI exit code BEFORE any side effect, so a report-write failure
    # can never silently mask a real regression.
    has_regression = any(r.verdict == DiffVerdict.regression for r in results)

    report_path = Path(store_dir) / "last-report.md"
    try:
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(render_pr_comment(results, from_model, to, n), encoding="utf-8")
        console.print(f"\n[dim]PR-style Markdown report written to {report_path}[/]")
    except OSError as exc:
        console.print(f"[yellow]warning:[/] could not write report to {report_path}: {exc}")

    if skipped:
        console.print(
            f"[yellow]note:[/] {len(skipped)} scenario(s) had no baseline and were skipped: "
            f"{', '.join(skipped)}. Re-run `mp baseline` to cover them."
        )

    if has_regression:
        raise typer.Exit(code=1)  # fail CI on a real regression


@app.command()
def report() -> None:
    """Run the public standard suite and draft a Modelpin Report. (Coming soon.)"""
    console.print(
        "[yellow]TODO[/]: the public Modelpin Report suite is not implemented yet. "
        "See docs/Modelpin-Engineering-Context-Pack.md section 7."
    )


def main() -> None:
    app()


if __name__ == "__main__":
    main()
