"""Modelpin CLI (Typer). Wires the pipeline end-to-end:

    modelpin scan      -> detector
    modelpin init      -> scaffold modelpin.yaml + scenarios/
    modelpin baseline  -> replay current model N times, persist traces
    modelpin check     -> replay a new model, diff vs baseline, print the PR-style report

Replays use the END USER's API key from the environment (BYO-key, spec section 9);
`--provider fake --fixtures <file>` runs the whole flow offline for demos/tests.
"""

from __future__ import annotations

import json
import shlex
from datetime import datetime, timezone
from pathlib import Path
from collections.abc import Sequence, Set as AbstractSet
from typing import NoReturn, Optional

import typer
from rich.box import ASCII as ASCII_BOX
from rich.console import Console
from rich.markup import escape as _rich_escape
from rich.table import Table

from modelpin import __version__
from modelpin.config import (
    DEFAULT_PROVIDER,
    DEFAULT_RUNS,
    ConfigError,
    ModelpinConfig,
    load_config,
)
from modelpin.demo import DEMO_DIRNAME, DEMO_FIXTURES, DEMO_TO, write_demo
from modelpin.detector import scan_repo
from modelpin.diff import (
    ALPHA,
    EQUIVALENCE_MODES,
    MIN_REFUSAL_DELTA,
    MIN_SEMANTIC_DELTA,
    MIN_TOOL_ARG_TVD,
    MIN_TOOL_TVD,
    diff_scenario,
)
from modelpin.diff.stats import (
    min_achievable_pvalue_distribution,
    min_achievable_pvalue_mean,
)
from modelpin.models import Assertion, DiffResult, DiffVerdict, Scenario, Trace
from modelpin.providers import ProviderAdapter, ProviderError, get_adapter, provider_help
from modelpin.providers.fake import FakeProvider
from modelpin.replay import replay
from modelpin.report import (
    ChannelCensus,
    ReportMeta,
    render_cli,
    render_pr_comment,
    render_report_md,
    to_report_sidecar,
)
from modelpin.report.suite import compute_suite_hash, read_manifest, slug
from modelpin.scenarios import _RESERVED_FILES as _RESERVED_IN_DIR
from modelpin.scenarios import ScenarioError, load_scenarios, unrecognised_assertion_keys
from modelpin.storage import (
    STORE_DIRNAME,
    BaselineError,
    load_baseline,
    nonuniform_run_counts,
    save_baseline,
)

#: A behavioral diff compares run *distributions*; fewer than this can't form one.
MIN_RUNS = 2
#: `mp check` exit code when at least one scenario could not be measured at all. Distinct
#: from 1 (a real regression) so a caller can tell "it broke" from "we could not tell", and
#: distinct from 2, which Click already returns for a usage error. See ADR-0018.
EXIT_UNMEASURED = 3
#: Below this, the permutation test is underpowered — warn but proceed. Derived from the
#: config default so the number a user is warned about and the number they get by default
#: can never disagree; three copies of it drifting apart is exactly what MP-03 was.
RECOMMENDED_RUNS = DEFAULT_RUNS
#: Tool-call trajectory match modes accepted by `--match` (validated at the CLI boundary
#: so an unknown mode fails friendly here rather than deep in the diff engine).
VALID_MATCH_MODES = ("strict", "unordered", "subset", "superset")

app = typer.Typer(
    help="Modelpin - Dependabot for AI models. Know before the model breaks you.",
    no_args_is_help=True,
    add_completion=False,
    rich_markup_mode=None,  # plain Click help: ASCII-only, never crashes on cp1252
)
console = Console()

_SAMPLE_SCENARIO = """{
  "id": "greeting",
  "name": "Simple greeting",
  "kind": "single",
  "input": {"messages": [{"role": "user", "content": "Say hello in one short sentence."}]},
  "assertions": {"must_contain": ["hello"]}
}
"""

# The scaffolded `runs:` is interpolated from DEFAULT_RUNS, not typed literally: the
# scaffold, the config default and the CLI warning were three copies of one number that
# drifted apart, which IS MP-03.
_SAMPLE_CONFIG = f"""# modelpin.yaml - generated by `modelpin init`. See docs/ for the full reference.
models:
  - gpt-4o-mini            # the model your app currently depends on (set yours)
scenarios_dir: scenarios
providers:
  - openai                 # uses YOUR OPENAI_API_KEY from the environment
runs: {DEFAULT_RUNS}                    # N replays per scenario; below 4 the tool signal cannot fire
judge_model: gpt-4o-mini   # semantic LLM-judge (optional; extra calls). Remove to disable.
# judge_provider: groq    # only needed when the judge model id does not name its own
#                         # vendor: gpt-* and gemini-* do, qwen/qwen3.8-27b does not.
"""


def _fail(message: str) -> NoReturn:
    console.print(f"[red]error:[/] {message}")
    raise typer.Exit(code=1)


def _adapter(provider: str, fixtures: Optional[str]) -> ProviderAdapter:
    try:
        if provider == "fake":
            return FakeProvider.from_fixtures(fixtures) if fixtures else FakeProvider()
        return get_adapter(provider)
    except FileNotFoundError as exc:
        _fail(f"fixtures file not found: {exc}")
    except ValueError as exc:  # unknown provider
        _fail(str(exc))


def _unimplemented_msg(provider: str) -> str:
    return (
        f"the {provider!r} adapter isn't implemented yet. Try `--provider fake "
        "--fixtures <file>` to run offline, or pick `--provider openai`."
    )


def _preflight_or_fail(adapter: ProviderAdapter, provider: str) -> None:
    """Fail before any tokens are spent if the provider isn't ready (key/SDK)."""
    try:
        adapter.preflight()
    except ProviderError as exc:
        _fail(str(exc))


def _guard_replay(provider: str, fn):
    """Run a replay step, converting adapter failures into friendly CLI errors."""
    try:
        return fn()
    except NotImplementedError:
        _fail(_unimplemented_msg(provider))
    except ProviderError as exc:
        _fail(str(exc))


def _replay_plan(
    count: int,
    src_dir: str,
    runs: int,
    provider: str,
    judge_model: Optional[str],
    sides: int = 1,
    ref_runs: Optional[int] = None,
) -> str:
    """Describe the size of the run that is ABOUT to happen, for the pre-spend line.

    The `>=` is load-bearing and must not be "tidied" into an exact count: one replay is one
    `adapter.run()`, but an agent scenario's replay drives a tool loop of up to
    `MAX_TOOL_TURNS` completions, so replays FLOOR the paid calls and never cap them.
    ADR-0019 governs this contract, including why `fake` must claim no cost at all.

    `sides` is how many models are replayed LIVE: 1 for `baseline` (which WRITES the store
    via `save_baseline` and has no reference side at all) and for `check` (whose reference
    traces come off disk), and 2 for `report`, which replays `--from` and `--to` both. It
    scales replays and therefore paid calls -- but deliberately NOT the judge axis, because
    `semantic_divergence_flags` scores every run on both sides regardless of where those
    traces came from. [M] MP-70: the same 14-scenario suite queues 70 replays under `check`
    and 140 under `report`. Both disclose `up to 140 judge calls` WHEN the reference side
    holds `runs` traces per scenario; see `ref_runs` below for when `check`'s does not.
    (That ceiling
    is deliberately loose: a real run needs at most 126, because an output identical to the
    modal baseline skips the judge -- `up to` is the honest word for a bound.) Deriving the
    judge count from `replays` would overstate `report`'s judge bill 2x -- the false-claim
    defect ADR-0019 rejects, merely pointed the other way.

    `ref_runs` is the TOTAL number of reference-side runs the judge will score, summed
    over the scenarios being replayed. It exists because `count * runs` is the CANDIDATE
    side's size and only accidentally the reference side's. `check` reads its reference
    traces off disk, and `load_baseline` returns however many runs were RECORDED --
    `--runs` bounds the replay, never the recording -- so a baseline taken at `--runs 20`
    and checked at `--runs 5` scores 20 reference runs, not 5. [M] MP-72: that pairing
    issues 24 judge calls for ONE scenario against a `2 x 1 x 5 = 10` disclosure. Left as
    None the reference side is assumed to be `count * runs`: VACUOUS for `baseline` (the
    judge clause never renders, so the value is unreachable) and EXACT for `report` (both
    sides come from `replay()`, so both are `runs` by construction) -- hence those two
    render byte-identically to before.
    Under-disclosing a paid axis is the same ADR-0019 violation as claiming an exact
    count, merely pointed the other way again.
    """
    replays = count * runs * sides
    plan = f"{count} scenario(s) from {src_dir}"
    if sides > 1:
        plan += f" x {sides} models"
    plan += f" -> {replays} replays"
    if provider == "fake":
        return plan  # canned traces, no network, nothing billed
    plan += f", >={replays} paid calls"
    if judge_model:
        judged = (count * runs if ref_runs is None else ref_runs) + count * runs
        plan += f" + up to {judged} judge calls"
    return plan


def _build_judge(provider: str, cfg: ModelpinConfig, to_model: str | None = None):
    """Construct + preflight the semantic LLM-judge if configured. Returns None when no
    judge_model is set or the run is offline (fake), so the diff stays purely structural."""
    if not cfg.judge_model or provider == "fake":
        return None
    try:
        from modelpin.judge import build_judge

        from modelpin.judge import infer_judge_provider

        # The judge is independent of the models being compared, so a cross-vendor check
        # (e.g. google vs openai) can still judge. MP-143: which HOST runs it is resolved
        # explicitly -- `judge_provider:` first, then an unambiguous model-id prefix, then
        # the REPLAY provider as the last resort. That last step is what makes the common
        # zero-config case work for a Groq-only user, who otherwise had no channel that
        # reads meaning at all; it is never a guess between two hosts, and the host is
        # printed below so the choice is visible before any of the user's money is spent.
        host = cfg.judge_provider or infer_judge_provider(cfg.judge_model) or provider
        judge = build_judge(cfg.judge_model, provider=host)
        judge.preflight()
    except (ProviderError, ImportError) as exc:
        _fail(f"semantic judge ({cfg.judge_model!r}): {exc}")
    console.print(f"[dim]semantic judge: {cfg.judge_model} on {host}[/]")
    if cfg.judge_model == to_model:
        # Not an error -- it can be a deliberate, cheap choice -- but a model judging its own
        # output is not an independent reading of it, and the north-star metric is the FP
        # RATE of what we publish. Say so once, at the point of choosing.
        console.print(
            "[yellow]note:[/] the judge model is the model being checked, so the semantic "
            "channel is not an independent reading. Prefer a different judge model."
        )
    return judge


def _load_config_or_fail(config_path: str) -> ModelpinConfig:
    try:
        return load_config(config_path)
    except ConfigError as exc:
        _fail(str(exc))


#: How the directory we searched was chosen — quoted back to the user, because
#: "no scenarios in 'examples/scenarios'" never said *who* asked for that path.
_SOURCE_LABEL = {
    "flag": "from --scenarios-dir",
    "config": "from scenarios_dir: in modelpin.yaml",
    "default": "the built-in default",
    "suite": "from --suite-dir",
}
_REPO_URL = "https://github.com/samarthputhraya/modelpin"


def _dir_state(p: Path) -> str:
    """Which of the states that `load_scenarios()` collapses into `[]` are we actually in?"""
    if not p.exists():
        return "that directory does not exist"
    if not p.is_dir():
        return "that path is a file, not a directory"
    jsons = sorted(p.glob("*.json"))
    if not jsons:
        return "it exists but contains no .json files"
    if all(f.name in _RESERVED_IN_DIR for f in jsons):
        names = ", ".join(f.name for f in jsons)
        return f"it contains only reserved files ({names}) and no scenario files"
    return "no .json file there loaded as a scenario"


def _init_target(config_path: str) -> Optional[Path]:
    """The scenarios dir `modelpin init` would actually create here, or None if unknowable."""
    try:
        sub = load_config(config_path).scenarios_dir if Path(config_path).exists() else "scenarios"
    except ConfigError:
        return None
    return (Path.cwd() / sub).resolve()


def _demo_hint(resolved: Path) -> str:
    """A generated demo sitting right next to the user is almost always what they meant.

    Without this, forgetting `cd modelpin-demo` sends a deliberately key-less user down the
    `modelpin init` path, which scaffolds a REAL provider config -- and the next command then
    demands a billed OPENAI_API_KEY, contradicting the "no API key" promise they just read.
    """
    for base in (Path.cwd(), resolved.parent):
        candidate = base / DEMO_DIRNAME
        if (candidate / DEMO_FIXTURES).is_file():
            return f"There is an offline demo right here: `cd {DEMO_DIRNAME}` first, then re-run. "
    return ""


def _scenarios_remedy(resolved: Path, source: str, config_path: str) -> str:
    """Advice that is TRUE in this state. `modelpin init` is only named when it would create
    exactly this path — otherwise the user follows it, succeeds, retries, and loops."""
    if source == "suite":
        return (
            "`modelpin init` does not create suite directories. The open public suite ships in "
            f"the repo, not in the wheel: clone {_REPO_URL} and pass "
            "--suite-dir <checkout>/examples/report-suite."
        )
    if resolved == _init_target(config_path):
        return _demo_hint(resolved) + (
            "Run `modelpin init` to scaffold it with a starter scenario, or "
            "`modelpin init --demo` "
            "for a runnable offline demo."
        )
    if source == "flag":
        return (
            "`modelpin init` will NOT create this path. Either add scenario *.json files there, "
            "or drop --scenarios-dir to use the directory from modelpin.yaml."
        )
    return (
        "`modelpin init` scaffolds the directory named by scenarios_dir: in modelpin.yaml, "
        "is not this path. Either add scenario *.json files here, or fix scenarios_dir:."
    )


def _fail_no_scenarios(raw: str, source: str, config_path: str) -> NoReturn:
    resolved = Path(raw).resolve()
    # _rich_escape: _fail() prints through Rich markup, so a path containing '[' would
    # otherwise be swallowed as a style tag and corrupt the very message meant to unstick
    # the user.
    _fail(
        f"no scenarios found in {_rich_escape(str(resolved))} ({_SOURCE_LABEL[source]}) -\n"
        f"       {_dir_state(Path(raw))}.\n"
        f"       {_scenarios_remedy(resolved, source, config_path)}"
    )


def _load_scenarios_or_fail(
    scenarios_dir: str, *, source: str, config_path: str = "modelpin.yaml"
) -> list[Scenario]:
    try:
        scenarios = load_scenarios(scenarios_dir)
    except ScenarioError as exc:
        _fail(str(exc))
    if not scenarios:
        _fail_no_scenarios(scenarios_dir, source, config_path)
    _warn_unrecognised_assertions(scenarios_dir)
    return scenarios


#: The assertion fields this version actually CHECKS, quoted back to the user when their file
#: declares something else. Read off the model so the message cannot drift from the code --
#: three hand-maintained copies of one list is the MP-03 shape, and MP-128 hit it again.
def _live_assertion_fields() -> str:
    return " / ".join(f"`{f}`" for f in Assertion.model_fields)


#: Keys MP-147 deleted, each with the remedy that is actually true for IT. Kept separate from
#: the generic "this version checks ..." line because that line is correct advice for a TYPO
#: and misleading for these two: neither has a `must_contain` equivalent.
_REMOVED_ASSERTION_KEYS: dict[str, str] = {
    "expected_tool_calls": (
        "removed in suite v3. The tool-TRAJECTORY channel already measures which tools a "
        "scenario calls, distributionally over N runs -- it always did the work this field "
        "appeared to. Delete the field; you lose nothing."
    ),
    "output_schema": (
        "removed in suite v3. No version ever checked it. For a structural claim about the "
        "output, assert a marker with `must_contain` / `must_not_contain`, or delete it."
    ),
}


def _warn_unrecognised_assertions(scenarios_dir: str) -> None:
    """Say once, per run, that a declared assertion key is not one this version checks.

    MP-142's defect was the word SILENTLY -- "a model field that silently does nothing is the
    same class of defect as a green tick over an unmeasured run". MP-147 then deleted the two
    dead fields (`expected_tool_calls`, `output_schema`), which alone would have made this
    WORSE for anyone with existing scenario files: pydantic ignores unknown keys, so their
    assertion would have gone from documented-but-inert to invisible. So the advisory moved
    with the fields -- it now reads the raw JSON rather than the parsed model, and therefore
    also catches a typo (`must_containn`) that no version has ever checked.

    A warning, not an error: refusing to run over an unknown key would turn a stale scenario
    file into a hard failure on upgrade, which is a worse trade than an honest note.
    """
    found = unrecognised_assertion_keys(scenarios_dir)
    if not found:
        return
    keys = ", ".join(f"`{k}`" for k in sorted(found))
    ids = sorted({sid for sids in found.values() for sid in sids})
    console.print(
        f"[yellow]note:[/] {len(ids)} scenario(s) declare {keys} under `assertions`, which "
        f"this version does not check -- no verdict, no exit code, and no coverage is derived "
        f"from them ({', '.join(_rich_escape(i) for i in ids)})."
    )
    # A key MP-147 REMOVED needs its own remedy. `[M]` first-run review, 2026-08-31: the
    # generic line below is right for a typo and WRONG for `expected_tool_calls` -- there is
    # no text assertion that expresses "expect this tool call", so a user reading it either
    # guesses the field is safe to delete or wastes time shoehorning a tool check into
    # `must_contain`. Say what actually does the job instead.
    for key in sorted(k for k in found if k in _REMOVED_ASSERTION_KEYS):
        console.print(f"[dim]  `{key}`: {_REMOVED_ASSERTION_KEYS[key]}[/]")
    if any(k not in _REMOVED_ASSERTION_KEYS for k in found):
        console.print(f"[dim]  this version checks {_live_assertion_fields()}.[/]")


def _scenarios_source(scenarios_dir: Optional[str], config_path: str) -> str:
    """Where the scenarios directory came from, for the error message to quote back."""
    if scenarios_dir:
        return "flag"
    return "config" if Path(config_path).exists() else "default"


def _resolve_provider(provider: Optional[str], cfg: ModelpinConfig) -> str:
    return provider or (cfg.providers[0] if cfg.providers else DEFAULT_PROVIDER)


def _resolve_runs(
    runs: Optional[int],
    cfg: ModelpinConfig,
    *,
    mode: str = "strict",
    baseline_sizes: Sequence[int] | None = None,
) -> int:
    n = cfg.runs if runs is None else runs  # an explicit --runs 0 must hit the floor, not coerce
    if n < MIN_RUNS:
        _fail(
            f"--runs must be >= {MIN_RUNS}: the diff compares run *distributions*, and "
            f"a single run can't form one (got {n})."
        )
    # ADR-0019 discloses the run SIZE before a command spends. A size that cannot reach
    # ALPHA is the same disclosure one level up: the user is about to pay for a run that is
    # structurally incapable of reporting a regression, and "less power" does not say that.
    # [M] MP-55: the shipped demo at `--runs 2` printed `OK 4 scenario(s) unchanged`, exit 0,
    # and wrote "looks safe to adopt" -- where the SAME fixtures at `--runs 5` find two
    # regressions and a minor.
    #
    # Priced on BOTH sides and on the MODE, or the warning becomes the very defect it exists
    # to prevent. [M] Pricing it on the candidate alone asserted "this run cannot report a
    # regression" over `baseline --runs 5` + `check --runs 2` -- an invocation that then
    # reported two regressions and exited 1, because the real 5v2 floor is 0.047619, below
    # ALPHA. [M] And the distribution floor only gates the tool/argument signals under the
    # EQUIVALENCE modes; the directional ones route through the mean statistic
    # (`diff/__init__.py`), so warning about them under `--match subset` was simply false --
    # reproduced firing a `subset` tool-call regression in the same invocation as the warning
    # that said it could not.
    nb = min(baseline_sizes) if baseline_sizes else n
    floor = min_achievable_pvalue_mean(nb, n)
    if floor > ALPHA:
        console.print(
            f"[bold yellow]warning:[/] at {nb} vs {n} runs/side the exact permutation test "
            f"cannot return a p-value below {floor:.3f}, so NO signal can reach p <= {ALPHA}. "
            f"[bold]This run cannot report a regression[/], whatever the models do. "
            f"Use --runs {RECOMMENDED_RUNS}."
        )
    elif mode in EQUIVALENCE_MODES and min_achievable_pvalue_distribution(nb, n) > ALPHA:
        dist_floor = min_achievable_pvalue_distribution(nb, n)
        console.print(
            f"[yellow]warning:[/] at {nb} vs {n} runs/side the tool-call and argument signals "
            f"cannot reach p <= {ALPHA} under `{mode}` (their floor is {dist_floor:.3f}). The "
            f"one-sided signals — refusal, format drift and the semantic judge — reach "
            f"{floor:.3f}. Use --runs {RECOMMENDED_RUNS}."
        )
    elif n < RECOMMENDED_RUNS:
        console.print(
            f"[yellow]warning:[/] only {n} runs/scenario; {RECOMMENDED_RUNS}+ gives the "
            "statistical diff real power and a lower false-positive rate."
        )
    return n


def _cannot_reach_alpha(nb: int, nc: int, mode: str) -> bool:
    """True when NO signal could have reached ``p <= ALPHA`` at these run counts (MP-55).

    Shared by ``check`` and ``report`` (MP-140) so one rule produces the disclosure on
    every surface. ``check`` reads ``nb`` off the STORED baseline, which can hold a
    different depth than ``--runs`` gives the candidate; ``report`` replays both sides
    itself, so ``nb == nc``.

    Priced on both sides and on the MODE. `[M]` The narrower trap is a MORE confident false
    clearance than the blunt one: at 3v3 `strict` the demo's ``refund_request`` -- whose
    only change is the tool-call trajectory -- rendered "no behavioral change" and "looks
    safe to adopt", while N=4 on identical fixtures reports a regression. The equivalence
    modes route the tool and argument signals through the two-sided test, whose floor is
    higher; the directional signals do not, so applying it under `subset`/`superset` would
    assert blindness about signals that can and do fire.
    """
    if min_achievable_pvalue_mean(nb, nc) > ALPHA:
        return True  # no signal at all could have fired
    return mode in EQUIVALENCE_MODES and min_achievable_pvalue_distribution(nb, nc) > ALPHA


def _exercised_tools(*sides: Sequence[Trace]) -> bool:
    """Did a tool actually get CALLED, on any run of any side?

    MP-159. This is the question the tool channel's liveness turns on, and
    ``Trace.tool_calls`` (`models.py`) is the only thing that can answer it. `[M]` The
    diff signal cannot: ``DiffSignals.tool_call_match`` reads **1.00** -- a perfect match --
    between two sides that each called zero tools, so a signal-based proxy would report the
    channel live in exactly the case it is dead.
    """
    return any(t.tool_calls for side in sides for t in side)


def _publish_report(markdown: str, store_dir: str, from_model: str, to: str) -> list[str]:
    """Write `last-report.md` and its durable archive copy; RETURN the notes to print.

    MP-160 extracted this because the zero-comparison exit paths did not write one. `[M]`
    A run whose scenarios are all un-baselined exits EXIT_UNMEASURED, and it used to leave
    the PREVIOUS run's `last-report.md` untouched -- which `action.yml` posts whenever it
    exists, independent of the exit code. CI published a stale verdict under a failing run.

    It returns its console notes rather than printing them so the CALLER can write the
    artifact first and print afterwards. `[M] 2026-09-01` that ordering is load-bearing: the
    console summary can raise `UnicodeEncodeError` on a cp1252 terminal, and while it printed
    first a crash there cost the artifact entirely.

    MP-150's write order is preserved: the stable path CI reads is written FIRST and the
    archive second, so if only one write can succeed it is the one CI reads.
    """
    notes: list[str] = []
    report_path = Path(store_dir) / "last-report.md"
    try:
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(markdown, encoding="utf-8")
        notes.append(
            f"[dim]PR-style Markdown report written to {_rich_escape(str(report_path))}[/]"
        )
    except OSError as exc:
        notes.append(
            f"[yellow]warning:[/] could not write report to "
            f"{_rich_escape(str(report_path))}: {_rich_escape(str(exc))}"
        )
        return notes
    try:
        archived = _archive_path(Path(store_dir), from_model, to)
        archived.write_text(markdown, encoding="utf-8")
        notes.append(f"[dim]archived for citation: {_rich_escape(str(archived))}[/]")
    except OSError as exc:
        notes.append(f"[yellow]warning:[/] could not archive the report: {_rich_escape(str(exc))}")
    return notes


def _channel_census(
    scenarios: Sequence[Scenario],
    judge: object | None,
    prov: str,
    *,
    tool_active: AbstractSet[str],
) -> ChannelCensus:
    """MP-138's census, read off the scenarios that were actually COMPARED (MP-140).

    Shared by ``check`` and ``report``. The judge half is read off the config; the TOOL half
    is read off the RECORDED TRACES, carried in by ``tool_active`` -- the ids whose runs
    actually called a tool.

    MP-159 replaced a declaration read with that trace read, for the reason this module
    already applies to refusal one screen below. `[M] 2026-08-31`, reproduced end to end on
    byte-identical fixtures: a scenario declaring one `tools` entry that NO run on either
    side ever called flipped `could not measure ... NOT cleared on content` into
    `no behavioral change ... looks safe to adopt` -- over a baseline of *"FRAUD DETECTED:
    block this transaction"* against a candidate of *"Looks fine, approve it. asdf qwerty
    zzzz garbage."* A declared tool that nothing calls sits in exactly the position
    ``hard_content_channels`` already excludes refusal for: it can only fire if the
    candidate STARTS calling tools, so a confident wrong answer never touches it. Counting
    it restored the false comfort this census exists to remove -- and the disclosure's own
    printed remedy, *"add `tools`"*, was what bought the green.

    ``tool_active`` is keyword-only with NO default on purpose. A caller that cannot supply
    traces must be made to say so at the call site: defaulting to "none exercised" would be
    safe in DIRECTION but would put a false sentence -- "no run called a tool" -- inside the
    disclosure that exists to be honest, which is the same defect one surface over.

    `[M]` The judge reason is computed HERE from the provider rather than inferred from
    ``judge is None`` downstream: the offline `fake` provider disables the judge regardless
    of config (``_build_judge``), so inferring "no judge_model configured" would put a false
    statement inside the disclosure that exists to be honest.
    """
    judge_enabled = judge is not None

    # MP-141. A scenario's OWN content coverage: the judge is suite-wide (one config key),
    # but a tool call happens per scenario, so with the judge off a scenario whose runs
    # called nothing has no CI-failing channel that reads content -- whatever its neighbours
    # did. MP-159 is the second half of that sentence: the trace must show a CALL, not just
    # the suite a declaration.
    #
    # BOTH halves are required, and the conjunction is the whole point of the shape. `[M]`
    # FP review BLOCKED the first cut, which tested `s.id in tool_active` alone: a scenario
    # with NO `tools` key whose traces nevertheless carry `tool_calls` went from HEAD's
    # "NOT cleared on content" to "looks safe to adopt" over the same content inversion --
    # MP-159's own defect, arriving through the other door in the same commit. That state is
    # not reachable from a live replay (both live adapters gate the request `tools` on
    # `scenario.input["tools"]`), but it is reachable from a hand-edited `traces.json` --
    # which `README.md` explicitly invites -- and from a baseline recorded before the `tools`
    # key was removed, since the store round-trips `tool_calls` faithfully.
    #
    # Requiring both makes the new blind set a SUPERSET of the old one for every input, so
    # this change can only ever withhold a clearance HEAD granted, never grant one HEAD
    # withheld. That monotonicity is the property that makes it safe to ship without new
    # calibration, and it is the same one MP-141 claimed for itself.
    def _tool_live(s: Scenario) -> bool:
        return bool(s.input.get("tools")) and s.id in tool_active

    blind = () if judge_enabled else tuple(s.id for s in scenarios if not _tool_live(s))
    return ChannelCensus(
        tools_exercised=any(_tool_live(s) for s in scenarios),
        # MP-159. The scenarios that ASKED for the tool channel and did not get it. Only the
        # remedy wording reads this, and that is the point: telling a user to "add `tools`"
        # when they already have is not merely useless, it is the advice that bought the
        # false clearance in the first place.
        declared_unused_tools=tuple(
            s.id for s in scenarios if s.input.get("tools") and s.id not in tool_active
        ),
        # MP-141. Read the fields the ENGINE reads, not the presence of an `Assertion`
        # object. `[M]` `diff/__init__.py` consults only `must_contain` / `must_not_contain`
        # (`structural.py::violates_text_assertions`). MP-147 deleted the two fields that
        # were read by nothing, so today an `Assertion` with neither live field set is an
        # EMPTY one -- which is still not coverage, and this check is still what says so.
        # `[M]` The shipped demo relied on the difference: `angry_customer` once carried an
        # `Assertion` whose only field was dead, and the old test counted it as armed in the
        # suite a brand-new user runs first.
        assertions_declared=any(
            s.assertions is not None
            and (s.assertions.must_contain or s.assertions.must_not_contain)
            for s in scenarios
        ),
        judge_enabled=judge_enabled,
        judge_off_reason=(
            "disabled on the offline `fake` provider"
            if prov == "fake"
            else "no `judge_model` configured"
        ),
        blind_scenarios=blind,
        compared=len(scenarios),
    )


def _resolve_match_mode(mode: str) -> str:
    if mode not in VALID_MATCH_MODES:
        _fail(f"--match must be one of {', '.join(VALID_MATCH_MODES)} (got {mode!r}).")
    return mode


@app.command()
def version() -> None:
    """Print the Modelpin version."""
    console.print(f"modelpin {__version__}")


@app.command()
def scan(path: str = typer.Argument(".", help="Repo root to scan.")) -> None:
    """Detect which AI models this repo depends on, and where."""
    hits = scan_repo(path)
    if not hits:
        console.print("No model identifiers found.")
        return
    table = Table("model", "file", "line", title="Models this repo depends on", box=ASCII_BOX)
    for h in sorted(hits, key=lambda x: (x["model"], x["file"], x["line"])):
        table.add_row(h["model"], h["file"], str(h["line"]))
    console.print(table)
    console.print(f"[dim]{len({h['model'] for h in hits})} distinct model(s).[/]")


@app.command()
def init(
    directory: str = typer.Argument(".", help="Repo to scaffold."),
    demo: bool = typer.Option(
        False,
        "--demo",
        help="Write a runnable offline demo instead of scaffolding this repo "
        "(no API key, no cost).",
    ),
) -> None:
    """Create modelpin.yaml + scenarios/ in the current repo (never overwrites)."""
    root = Path(directory)

    if demo:
        written = write_demo(root)
        if written:
            console.print("[green]Offline demo written:[/]")
            for p in written:
                console.print(f"  - {p}")
        else:
            console.print(f"[dim]{root / DEMO_DIRNAME} already exists; left untouched.[/]")
        console.print("\nNext, run these three lines:")
        console.print(f"  [bold]cd {DEMO_DIRNAME}[/]")
        console.print(f"  [bold]modelpin baseline --fixtures {DEMO_FIXTURES}[/]")
        console.print(f"  [bold]modelpin check --to {DEMO_TO} --fixtures {DEMO_FIXTURES}[/]")
        console.print(
            f"\n[dim]`modelpin check` exits 1 there on purpose - that is the CI gate. "
            f"See {DEMO_DIRNAME}/README.md.[/]"
        )
        return

    cfg_path = root / "modelpin.yaml"
    # Honour an existing modelpin.yaml's scenarios_dir. Hardcoding "scenarios" here made
    # `mp init` scaffold a directory the rest of the CLI would then not read — the second
    # no-exit loop: the error says run `mp init`, `mp init` succeeds, nothing changes.
    sub = "scenarios"
    if cfg_path.exists():
        try:
            sub = load_config(cfg_path).scenarios_dir
        except ConfigError as exc:
            _fail(str(exc))
    scenarios_dir = root / sub

    created: list[str] = []
    if not cfg_path.exists():
        cfg_path.write_text(_SAMPLE_CONFIG, encoding="utf-8")
        created.append(str(cfg_path))
    scenarios_dir.mkdir(parents=True, exist_ok=True)
    # Reserved-aware, and it must stay that way: `_dir_state()` reports a dir holding
    # only manifest.json as having no scenarios, so if this check disagrees, `init`
    # silently writes nothing and the error's advice loops forever. That is the exact
    # defect class MP-01 was about, reintroduced one function away.
    existing = [f for f in scenarios_dir.glob("*.json") if f.name not in _RESERVED_IN_DIR]
    if not existing:
        (scenarios_dir / "greeting.json").write_text(_SAMPLE_SCENARIO, encoding="utf-8")
        created.append(str(scenarios_dir / "greeting.json"))
    if created:
        console.print("[green]Scaffolded:[/]")
        for c in created:
            console.print(f"  - {c}")
        console.print("\nNext: add scenarios, then run [bold]modelpin baseline[/].")
        console.print(
            "[dim]No API key yet? Run `modelpin init --demo` for a free offline walkthrough.[/]"
        )
    else:
        # MP-32: this branch means `init` ADOPTED a config it did not write. Reporting a bare
        # "already initialised" let a cloned repo's config hand the user a scenario set they
        # had never seen, which `baseline` then replayed on their key. Name what was adopted.
        # `existing` is not stale here: this branch means nothing was created, so no
        # greeting.json was written after the glob.
        console.print(f"Already initialised (modelpin.yaml + {sub}/ present).")
        console.print(
            f"[dim]{len(existing)} scenario(s) in {sub}/ - `modelpin baseline` replays "
            f"all of them on your own key. Not yours? Check {cfg_path}.[/]"
        )


@app.command()
def baseline(
    model: Optional[str] = typer.Option(
        None, "--model", help="Model to baseline (default: config)."
    ),
    provider: Optional[str] = typer.Option(None, "--provider", help=provider_help()),
    fixtures: Optional[str] = typer.Option(
        None, "--fixtures", help="Canned traces for --provider fake (required with it)."
    ),
    runs: Optional[int] = typer.Option(None, "--runs", help="Replays per scenario."),
    config_path: str = typer.Option("modelpin.yaml", "--config"),
    scenarios_dir: Optional[str] = typer.Option(None, "--scenarios-dir"),
    store_dir: str = typer.Option(STORE_DIRNAME, "--store-dir"),
) -> None:
    """Record current model behavior for your scenarios (N runs)."""
    cfg = _load_config_or_fail(config_path)
    src_dir = scenarios_dir or cfg.scenarios_dir
    scenarios = _load_scenarios_or_fail(
        src_dir,
        source=_scenarios_source(scenarios_dir, config_path),
        config_path=config_path,
    )
    from_model = model or (cfg.models[0] if cfg.models else None)
    if not from_model:
        _fail("no model to baseline. Pass --model or set `models:` in modelpin.yaml.")
    n = _resolve_runs(runs, cfg)
    prov = _resolve_provider(provider, cfg)
    adapter = _adapter(prov, fixtures)
    plan = _replay_plan(len(scenarios), src_dir, n, prov, judge_model=None)
    console.print(f"[dim]provider={prov} model={from_model} runs={n} | {plan}[/]")
    _preflight_or_fail(adapter, prov)
    traces = _guard_replay(
        prov, lambda: {s.id: replay(s, from_model, adapter, runs=n) for s in scenarios}
    )
    path = save_baseline(traces, from_model, store_dir)
    console.print(
        f"[green]Baseline recorded[/] for [bold]{from_model}[/]: "
        f"{len(scenarios)} scenario(s) x{n} runs -> {path}"
    )


@app.command()
def check(
    to: str = typer.Option(..., "--to", help="The new model id to test against your baseline."),
    from_: Optional[str] = typer.Option(None, "--from", help="Baseline model (default: config)."),
    provider: Optional[str] = typer.Option(None, "--provider", help=provider_help()),
    fixtures: Optional[str] = typer.Option(
        None, "--fixtures", help="Canned traces for --provider fake (required with it)."
    ),
    runs: Optional[int] = typer.Option(None, "--runs", help="Replays per scenario."),
    mode: str = typer.Option(
        "strict", "--match", help="Tool-call match mode: strict|unordered|subset|superset."
    ),
    config_path: str = typer.Option("modelpin.yaml", "--config"),
    scenarios_dir: Optional[str] = typer.Option(None, "--scenarios-dir"),
    store_dir: str = typer.Option(STORE_DIRNAME, "--store-dir"),
) -> None:
    """Replay scenarios on a new model and report behavioral regressions.

    Exit codes: 0 = no regression. 1 = at least one real regression (the CI gate).
    3 = the run could not answer -- a scenario that WAS compared could not be measured, OR
    the provider rejected a scenario, OR nothing could be compared at all (no usable
    baseline; every scenario skipped or rejected). 3 is deliberately not 1: "we could not
    tell" is a different claim from "it broke". A configuration error is neither: no
    scenarios found exits 1, and a bad flag exits 2, which is Click's usage code.

    A scenario with no recorded baseline is the deliberate exception: it is named in the
    report, on the console and in the archive, and it removes the affirmative clearance, but
    it does not by itself fail the build. `[M]` Precisely: it does not change the exit code,
    so a run keeps whatever its COMPARED scenarios earned -- 0 if they were clean, 1 if one
    of them regressed. Only when NOTHING is left to compare does the run abstain with 3.
    Reasoning, options and revisit trigger: ADR-0033.
    """
    # `[M]` first-run review, 2026-08-31: the exit codes were documented in the README and in
    # `action.yml` and NOWHERE in `--help` -- which is where someone staring at a nonzero exit
    # in a CI log actually looks. Kept short above on purpose: the rationale belongs here, the
    # user-facing surface gets the answer.
    mode = _resolve_match_mode(mode)
    cfg = _load_config_or_fail(config_path)
    src_dir = scenarios_dir or cfg.scenarios_dir
    scenarios = _load_scenarios_or_fail(
        src_dir,
        source=_scenarios_source(scenarios_dir, config_path),
        config_path=config_path,
    )
    from_model = from_ or (cfg.models[0] if cfg.models else None)
    if not from_model:
        _fail("no baseline model. Pass --from or set `models:` in modelpin.yaml.")
    # Resolved ABOVE the baseline load so the abstain branch below can publish an artifact.
    prov = _resolve_provider(provider, cfg)
    try:
        base = load_baseline(from_model, store_dir)
    except (FileNotFoundError, BaselineError) as e:
        # EXIT_UNMEASURED, not 1. `[M] 2026-09-01` claims review: with no usable baseline the
        # run replays nothing and compares nothing, and this exited **1** -- so `action.yml`
        # took its else-branch and annotated the PR with "Modelpin detected a behavioral
        # regression migrating to 'X'" over a run that never called a model. A false claim
        # about someone's model, posted into their PR: the same class MP-160 fixed one
        # instance of, reached through the setup path instead of the scenario path. ADR-0018:
        # a run that measured nothing abstains.
        console.print(f"[yellow]could not measure:[/] {_rich_escape(str(e))}")
        # `[M] 2026-09-01` This was the THIRD zero-comparison exit, and the only one still
        # writing nothing -- the very defect `_publish_report` was extracted to remove, one
        # branch from the extraction, added by the same commit. `action.yml` posts
        # `last-report.md` whenever it exists with no reference to the exit code, so the
        # PREVIOUS run's red header was republished under a run that never called a model.
        # Every scenario is un-baselined here by construction, so all of them are skipped.
        for _note in _publish_report(
            render_pr_comment(
                [], from_model, to, runs or cfg.runs, prov, (), None, (), [x.id for x in scenarios]
            ),
            store_dir,
            from_model,
            to,
        ):
            console.print(_note)
        raise typer.Exit(code=EXIT_UNMEASURED)
    # [M] MP-116: an uneven baseline is scored correctly per scenario (MP-72), but it splits
    # the run into a measured half and a structurally blind half, and NOTHING said so -- the
    # posted report then led with a green clearance. Reported, not raised: `load_baseline` is
    # right not to fail over a file it can use, and the user can act on this before spending.
    # Printed BEFORE the pre-spend disclosure below, which prices the whole run off
    # `min(baseline_sizes)` and so describes the weakest scenario, not every one.
    uneven = nonuniform_run_counts(base, [s.id for s in scenarios])
    if uneven:
        # `escape`, not raw: `[M]` a first-run review crashed `mp check` with an unhandled
        # rich MarkupError and a full traceback (exit 1, no warning printed) on a scenario
        # id containing a lone `[/]`. Scenario ids are author-controlled text and reach
        # every console string through this path; `report/render_cli` already escapes them.
        detail = ", ".join(f"{_rich_escape(sid)}={k}" for sid, k in sorted(uneven.items()))
        console.print(
            f"[yellow]warning:[/] the baseline for '{from_model}' holds different numbers of "
            f"recorded runs per scenario ({detail}), so statistical power differs between "
            f"them and some may be unable to report a regression at all. Re-record with "
            f"`modelpin baseline --runs {RECOMMENDED_RUNS}` for uniform coverage."
        )
    n = _resolve_runs(runs, cfg, mode=mode, baseline_sizes=[len(v) for v in base.values() if v])
    adapter = _adapter(prov, fixtures)
    # Only scenarios that HAVE a baseline are replayed (the rest are skipped below), so
    # count those - an inflated pre-spend number is its own kind of false claim. MP-32.
    billable = sum(1 for s in scenarios if base.get(s.id))
    # The judge scores the STORED baseline runs, however many were recorded -- `--runs`
    # bounds this run's replays, not a past run's recording. Counting the traces on disk
    # rather than assuming `n` of them is what keeps `up to N judge calls` a bound when a
    # 20-run baseline is checked at `--runs 5`. MP-72.
    ref_runs = sum(len(t) for t in (base.get(s.id) or [] for s in scenarios))
    plan = _replay_plan(billable, src_dir, n, prov, cfg.judge_model, ref_runs=ref_runs)
    console.print(
        f"[dim]provider={prov} from={from_model} to={to} runs={n} match={mode} | {plan}[/]"
    )
    _preflight_or_fail(adapter, prov)
    judge = _build_judge(prov, cfg, to_model=to)

    results = []
    skipped: list[str] = []
    #: MP-159. Scenario ids whose runs ACTUALLY called a tool, on either side. Accumulated
    #: in the replay loop because that is the only place both sides' traces exist: `cand` is
    #: a loop local and `DiffResult` carries no traces, so a census computed after the loop
    #: has nothing left to read and used to fall back on the declaration.
    tool_active: set[str] = set()
    #: (scenario_id, provider message) for scenarios the provider REFUSED outright. A
    #: different condition from `skipped` (no baseline recorded) and from an
    #: `insufficient_evidence` verdict (replayed, but nothing usable came back).
    rejected: list[tuple[str, str]] = []

    def _run_check() -> None:
        for s in scenarios:
            base_traces = base.get(s.id)
            if not base_traces:
                skipped.append(s.id)
                continue
            try:
                cand = replay(s, to, adapter, runs=n)
            except ProviderError as exc:
                # MP-148. One scenario the provider rejects must not delete the others.
                # `[M] 2026-08-31` three hard 400s on the live aegis run each killed all six
                # scenarios and produced NOTHING -- including one where the model
                # HALLUCINATED a tool name, which is itself the behaviour change this tool
                # exists to catch. `report` already survived this; `check`, the command CI
                # runs, did not. Deliberately NOT a retry (that is MP-139's rule, and a 400
                # must still not be retried): skip, disclose, and refuse to call the run
                # clean. ProviderError messages are key-scrubbed by the adapters.
                console.print(
                    # repr FIRST, then escape. `[M] 2026-09-01` the other order is a LIVE
                    # crash: escaping inserts a backslash before the bracket, then repr
                    # doubles that backslash, and rich re-parses the result as a literal
                    # backslash followed by a live `[/]` tag. Inherited from MP-148; the
                    # sibling site in `report()` already uses this order.
                    f"[yellow]note:[/] scenario {_rich_escape(repr(s.id))} could not be "
                    f"replayed: {_rich_escape(str(exc))}"
                )
                rejected.append((s.id, str(exc)))
                continue
            if _exercised_tools(base_traces, cand):
                tool_active.add(s.id)
            results.append(
                diff_scenario(s.id, from_model, to, base_traces, cand, s, mode, judge=judge)
            )

    # NotImplementedError stays a HARD failure: an unimplemented adapter is a config error
    # that would fail every scenario identically, so swallowing it per scenario would turn a
    # misconfigured run into a silent no-op instead of an answerable message (MP-128).
    _guard_replay(prov, _run_check)

    if not results:
        # MP-160. Three ways to compare nothing, and they used to be told apart wrongly.
        # `[M] 2026-08-31` with EVERY scenario un-baselined this fell to `_fail` and exited
        # **1** -- the code that means REGRESSION -- over a run that compared nothing at all.
        # ADR-0018 is explicit that a run which measured nothing ABSTAINS, and `action.yml`
        # cannot tell exit 1 from exit 1, so a stale baseline was indistinguishable in CI
        # from a caught regression. It is EXIT_UNMEASURED now, on every branch below.
        #
        # `[M]` The old message also lied under a MIXED cause: with one rejection and one
        # missing baseline it printed "the provider rejected all 1 scenario(s)", which is
        # false about the other one, and the `skipped` ids never reached the console at all
        # because the note that would have named them sits further down, past this raise.
        # The pre-MP-148 path had the opposite bug -- it sent a user whose provider had
        # refused every scenario to `modelpin baseline`, advice for a condition they were
        # not in. Say exactly what happened, name both causes, and abstain.
        _why = []
        if rejected:
            _why.append(f"the provider rejected {len(rejected)} scenario(s)")
        if skipped:
            _why.append(f"{len(skipped)} scenario(s) had no recorded baseline")
        detail = " and ".join(_why) if _why else "no scenario produced a comparison"
        console.print(f"[yellow]could not measure:[/] nothing was compared -- {detail}.")
        if skipped:
            console.print(
                f"[dim]   no baseline: {_rich_escape(', '.join(skipped))}. "
                f"Record one with `modelpin baseline`.[/]"
            )
        # `[M]` This path wrote NO artifact, so the PREVIOUS run's `last-report.md` stayed on
        # disk as the reviewer-facing verdict -- and `action.yml` posts that file whenever it
        # exists, regardless of the exit code. A run that compared nothing has to say so in
        # the artifact, not only on a console nobody reads.
        _publish_report(
            render_pr_comment([], from_model, to, n, prov, (), None, rejected, skipped),
            store_dir,
            from_model,
            to,
        )
        raise typer.Exit(code=EXIT_UNMEASURED)

    # MP-55. Which scenarios were compared at run counts where NO signal could reach ALPHA?
    # Computed per scenario, because a stored baseline can hold a different number of runs
    # than `--runs` gives the candidate (`baseline --runs 5` then `check --runs 2` is 5v2),
    # and the permutation floor depends on BOTH sides.
    def _blind(sid: str) -> bool:
        return _cannot_reach_alpha(len(base[sid]), n, mode)

    # The scenarios that actually produced `results` -- a scenario with no stored baseline is
    # skipped above and never diffed. Both disclosures below must be read off THIS set, or
    # they describe a run that did not happen.
    # ...and NOT the ones the provider rejected: a scenario that never replayed was never
    # measured, so counting it here would price coverage for a run that did not happen.
    # MP-138 shipped exactly that mistake once and review caught it; MP-148 is the same
    # trap with a new cause.
    _rejected_ids = {sid for sid, _ in rejected}
    compared = [s for s in scenarios if base.get(s.id) and s.id not in _rejected_ids]
    underpowered = [s.id for s in compared if _blind(s.id)]

    # MP-138. `underpowered` above prices RUN COUNT. This prices CHANNEL AVAILABILITY --
    # the other way a run can be structurally unable to fail, and one `_resolve_runs`
    # cannot see because it is not a function of N.
    census = _channel_census(compared, judge, prov, tool_active=tool_active)

    _summary = render_cli(results, from_model, to, n, underpowered, census, rejected, skipped)

    # Decide the CI exit code BEFORE any side effect, so a report-write failure
    # can never silently mask a real regression.
    has_regression = any(r.verdict == DiffVerdict.regression for r in results)
    unmeasured = [r for r in results if r.verdict == DiffVerdict.insufficient_evidence]

    # MP-160. The artifact is written BEFORE the console summary prints, because
    # `[M] 2026-09-01` the new `skipped` console block put scenario ids on the terminal ahead
    # of the report write for the first time -- and on a cp1252 console (Windows CI with
    # piped stdout) an id outside Latin-1 raises `UnicodeEncodeError` there, which used to
    # cost the artifact entirely and let `action.yml` republish the previous run's verdict.
    # The housekeeping notes are held and printed after the summary, so reading order is
    # unchanged: verdict first, file paths after.
    markdown = render_pr_comment(
        results, from_model, to, n, prov, underpowered, census, rejected, skipped
    )
    _publish_notes = _publish_report(markdown, store_dir, from_model, to)
    console.print(_summary)
    for _note in _publish_notes:
        console.print(_note)

    if skipped:
        # MP-160. `escape`d: `Scenario.id` has no pattern validator (`models.py`), and
        # `[M] 2026-08-31` an id containing `[/]` raised `MarkupError` HERE and aborted the
        # command -- after the report and the archive had already been written, so CI
        # published the artifact and then failed on a markup typo. `[M]` Review corrected an
        # earlier version of this comment, which claimed this was the file's LAST unescaped
        # join: `report()` carried two more, and `modelpin report` aborted the same way. Both
        # are escaped below. The ROOT cause is still open -- `_fail` prints its message
        # through rich unescaped (MP-170), which is how a provider error carrying a scenario
        # id crashes `modelpin baseline`.
        console.print(
            f"[yellow]note:[/] {len(skipped)} scenario(s) had no baseline and were skipped: "
            f"{_rich_escape(', '.join(skipped))}. Re-run `modelpin baseline` to cover them."
        )

    if has_regression:
        raise typer.Exit(code=1)  # fail CI on a real regression
    if unmeasured or rejected:
        # `rejected` (MP-148) rides the same exit as `insufficient_evidence`: both mean the
        # suite did not fully answer the question. Deliberately BELOW the regression check --
        # a real regression in the scenarios that DID run is still the strongest true claim
        # available, and downgrading it to "could not measure" because a sibling scenario
        # 400'd would hide the finding CI exists to surface.
        # EXIT_UNMEASURED, not 1: a run that measured nothing is not a regression, and
        # reporting it as one would put a false claim in the Action's PR comment. Not 2
        # either -- Click already uses 2 for a usage error, so `mp check --bogus` exits 2.
        # The Action gates on `code != '0'`, so CI still fails without any workflow change.
        raise typer.Exit(code=EXIT_UNMEASURED)


#: Per-run `check` reports, kept beside the stable `last-report.md` so a run's evidence
#: survives the next run (MP-150). Under the store dir, not the working tree: it holds
#: measurements about a model, which is what `.modelpin/` already is.
REPORT_ARCHIVE_DIRNAME = "runs"


def _archive_path(store: Path, from_model: str, to_model: str, stamp: str | None = None) -> Path:
    """A collision-free, citable path for THIS run's report.

    The name has to be readable back to a run -- both model ids and the UTC instant -- or it
    is a file, not a citation. Timestamps are one second wide and CI runs are fast, so a
    same-second collision disambiguates with a counter rather than clobbering: overwriting is
    the entire defect this function exists to remove.
    """
    stamp = stamp or datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    directory = store / REPORT_ARCHIVE_DIRNAME
    directory.mkdir(parents=True, exist_ok=True)
    stem = f"check-{slug(from_model)}-to-{slug(to_model)}-{stamp}"
    candidate = directory / f"{stem}.md"
    n = 2
    while candidate.exists():
        candidate = directory / f"{stem}-{n}.md"
        n += 1
    return candidate


#: Where rendered Modelpin Reports (.md + .json) are written by default.
#: There is deliberately no DEFAULT_REPORT_SUITE: the wheel ships no scenarios at all,
#: so any built-in default would name a path that cannot exist after `pip install`, and the
#: user would be told "no scenarios found" for a directory they never asked for.
DEFAULT_REPORT_OUTPUT = "reports"


def _report_basename(candidate: str, reference: str, date_iso: str) -> str:
    """Deterministic report filename stem. Same-model runs drop the `-vs-` segment."""
    if candidate == reference:
        return f"modelpin-report-{slug(candidate)}-{date_iso}"
    return f"modelpin-report-{slug(candidate)}-vs-{slug(reference)}-{date_iso}"


@app.command()
def report(
    to: str = typer.Option(..., "--to", help="The new/launching model id to report on."),
    from_: str = typer.Option(
        ...,
        "--from",
        help="Reference/incumbent model to compare against (pass the same id as --to for a "
        "baseline characterization).",
    ),
    provider: Optional[str] = typer.Option(None, "--provider", help=provider_help()),
    fixtures: Optional[str] = typer.Option(
        None, "--fixtures", help="Canned traces for --provider fake (required with it)."
    ),
    runs: Optional[int] = typer.Option(None, "--runs", help="Replays per scenario per model."),
    mode: str = typer.Option(
        "strict", "--match", help="Tool-call match mode: strict|unordered|subset|superset."
    ),
    suite_dir: str = typer.Option(
        ...,
        "--suite-dir",
        help="Public scenario suite directory (required; the open suite lives in the repo).",
    ),
    config_path: str = typer.Option("modelpin.yaml", "--config"),
    output_dir: str = typer.Option(
        DEFAULT_REPORT_OUTPUT, "--output-dir", help="Directory for the .md + .json report."
    ),
) -> None:
    """Run the open public suite across two models and draft a reproducible Modelpin Report.

    Unlike `modelpin check`, this never fails CI on a regression — it *publishes* findings. Both
    models are replayed live with YOUR API key (BYO-key); the report is framed as
    measurement/opinion ("on our open suite, under these settings, we observed…").
    """
    mode = _resolve_match_mode(mode)
    cfg = _load_config_or_fail(config_path)
    scenarios = _load_scenarios_or_fail(suite_dir, source="suite", config_path=config_path)
    # `mode=` is passed for the same reason `check` passes it, and MP-140 makes it
    # load-bearing: the Report now publishes an `underpowered` list computed with the mode,
    # so a pre-spend warning priced WITHOUT it would stay silent about the blindness the
    # document it is about to write goes on to disclose. Both sides are replayed here at
    # `n`, so `baseline_sizes` correctly defaults to it.
    n = _resolve_runs(runs, cfg, mode=mode)
    prov = _resolve_provider(provider, cfg)
    adapter = _adapter(prov, fixtures)
    # Both sides are replayed live here, so the REPLAYS are twice a `check` over the same
    # suite. The JUDGE axis is not -- `check` reads its reference side off disk, so its judge
    # figure tracks the stored baseline's depth (ADR-0026). User's own key (ADR-0008).
    plan = _replay_plan(len(scenarios), suite_dir, n, prov, cfg.judge_model, sides=2)
    console.print(f"[dim]provider={prov} from={from_} to={to} runs={n} match={mode} | {plan}[/]")
    _preflight_or_fail(adapter, prov)
    judge = _build_judge(prov, cfg, to_model=to)

    results: list[DiffResult] = []
    skipped: list[str] = []
    tool_active: set[str] = set()  # MP-159, as in `check`: read off the traces, not the suite
    for s in scenarios:
        try:
            base_traces = replay(s, from_, adapter, runs=n)
            cand_traces = replay(s, to, adapter, runs=n)
        except NotImplementedError:
            _fail(
                _unimplemented_msg(prov)
            )  # an unimplemented adapter is a config error, not a skip
        except ProviderError as exc:
            # One scenario failing must not sink the whole report — it documents findings.
            # ProviderError messages are already key-scrubbed by the adapters.
            # `_rich_escape` on BOTH: a scenario id has no pattern validator and a provider
            # message is remote text. MP-160 found this pair by disproving its own comment.
            console.print(
                f"[yellow]note:[/] scenario {_rich_escape(repr(s.id))} skipped: "
                f"{_rich_escape(str(exc))}"
            )
            skipped.append(s.id)
            continue
        if _exercised_tools(base_traces, cand_traces):
            tool_active.add(s.id)
        results.append(
            diff_scenario(s.id, from_, to, base_traces, cand_traces, s, mode, judge=judge)
        )

    if not results:
        _fail("no scenarios completed; nothing to report.")

    # MP-140 / MP-123. Both coverage axes, computed on the scenarios that actually produced
    # a comparison -- a scenario the provider failed on is in `skipped` and was never
    # diffed, so reading either disclosure off the LOADED suite would describe a run that
    # did not happen. (MP-138 shipped that mistake on `check` and it was caught in review.)
    #
    # Unlike `check`, this command replays BOTH sides itself at `n`, so the permutation
    # floor is identical for every scenario and blindness is all-or-nothing here. It is
    # still materialised per scenario: the renderers name the blind ones, and a future
    # per-scenario run count must not need this call site changed to stay honest.
    compared = [s for s in scenarios if s.id not in set(skipped)]
    underpowered = [s.id for s in compared] if _cannot_reach_alpha(n, n, mode) else []
    census = _channel_census(compared, judge, prov, tool_active=tool_active)

    console.print(render_cli(results, from_, to, n, underpowered, census))

    suite_id, suite_version = read_manifest(suite_dir)
    date_iso = datetime.now(timezone.utc).date().isoformat()
    # Shell-quote each value so the copy-paste reproduce command survives model ids or paths
    # containing spaces/parentheses (POSIX quoting, for the bash/CI context the tool targets).
    reproduce_cmd = (
        f"modelpin report --to {shlex.quote(to)} --from {shlex.quote(from_)} "
        f"--provider {shlex.quote(prov)} --runs {n} --match {shlex.quote(mode)} "
        f"--suite-dir {shlex.quote(suite_dir)}"
    )
    meta = ReportMeta(
        suite_id=suite_id,
        suite_version=suite_version,
        suite_hash=compute_suite_hash(scenarios),
        suite_path=suite_dir,
        candidate_model=to,
        reference_model=from_,
        provider=prov,
        runs=n,
        judge_model=cfg.judge_model if judge is not None else "disabled",
        match_mode=mode,
        modelpin_version=__version__,
        diff_thresholds={
            "alpha": ALPHA,
            "min_tool_tvd": MIN_TOOL_TVD,
            # ADR-0009: a public Report must publish every floor that gated a verdict in it.
            # The argument floor is advisory-only (ADR-0029) but it still GATES -- omitting it
            # hands the reader an `Arg match` number and a `changed_minor` verdict with no way
            # to tell which threshold produced them.
            "min_tool_arg_tvd": MIN_TOOL_ARG_TVD,
            "min_refusal_delta": MIN_REFUSAL_DELTA,
            "min_semantic_delta": MIN_SEMANTIC_DELTA,
        },
        date_iso=date_iso,
        reproduce_cmd=reproduce_cmd,
        scenario_ids=[s.id for s in scenarios],
        skipped=skipped,
        # MP-140. Carried on the meta so the Markdown and the JSON audit trail get it from
        # one place; passing it to the renderer alone is how `check` ended up honest and the
        # published Report did not.
        census=census,
        underpowered=underpowered,
    )

    out = Path(output_dir)
    base = _report_basename(to, from_, date_iso)
    md_path = out / f"{base}.md"
    json_path = out / f"{base}.json"
    try:
        out.mkdir(parents=True, exist_ok=True)
        md_path.write_text(render_report_md(results, meta), encoding="utf-8")
        json_path.write_text(
            json.dumps(to_report_sidecar(results, meta), indent=2), encoding="utf-8"
        )
        console.print(f"\n[green]Modelpin Report written[/] -> {md_path}")
        console.print(f"[dim]raw results (JSON) -> {json_path}[/]")
    except OSError as exc:
        console.print(f"[yellow]warning:[/] could not write report to {out}: {exc}")

    if skipped:
        console.print(
            f"[yellow]note:[/] {len(skipped)} scenario(s) skipped and excluded from the "
            f"report counts: {_rich_escape(', '.join(skipped))}."
        )
    # NB: report() never exits non-zero on a regression — it publishes findings, not a CI gate.


def main() -> None:
    app()


if __name__ == "__main__":
    main()
