"""Modelpin CLI (Typer). Wires the pipeline end-to-end:

    modelpin scan      -> detector
    modelpin init      -> scaffold modelpin.yaml + scenarios/
    modelpin baseline  -> replay current model N times, persist traces
    modelpin check     -> replay a new model, diff vs baseline, print the PR-style report

Replays use the END USER's API key from the environment (BYO-key, spec section 9);
`--provider fake --fixtures <file>` runs the whole flow offline for demos/tests.
"""

from __future__ import annotations

import json
import shlex
from datetime import datetime, timezone
from pathlib import Path
from collections.abc import Sequence
from typing import NoReturn, Optional

import typer
from rich.box import ASCII as ASCII_BOX
from rich.console import Console
from rich.markup import escape as _rich_escape
from rich.table import Table

from modelpin import __version__
from modelpin.config import (
    DEFAULT_PROVIDER,
    DEFAULT_RUNS,
    ConfigError,
    ModelpinConfig,
    load_config,
)
from modelpin.demo import DEMO_DIRNAME, DEMO_FIXTURES, DEMO_TO, write_demo
from modelpin.detector import scan_repo
from modelpin.diff import (
    ALPHA,
    EQUIVALENCE_MODES,
    MIN_REFUSAL_DELTA,
    MIN_SEMANTIC_DELTA,
    MIN_TOOL_ARG_TVD,
    MIN_TOOL_TVD,
    diff_scenario,
)
from modelpin.diff.stats import (
    min_achievable_pvalue_distribution,
    min_achievable_pvalue_mean,
)
from modelpin.models import DiffResult, DiffVerdict, Scenario
from modelpin.providers import ProviderAdapter, ProviderError, get_adapter
from modelpin.providers.fake import FakeProvider
from modelpin.replay import replay
from modelpin.report import (
    ReportMeta,
    render_cli,
    render_pr_comment,
    render_report_md,
    to_report_sidecar,
)
from modelpin.report.suite import compute_suite_hash, read_manifest, slug
from modelpin.scenarios import _RESERVED_FILES as _RESERVED_IN_DIR
from modelpin.scenarios import ScenarioError, load_scenarios
from modelpin.storage import STORE_DIRNAME, BaselineError, load_baseline, save_baseline

#: A behavioral diff compares run *distributions*; fewer than this can't form one.
MIN_RUNS = 2
#: `mp check` exit code when at least one scenario could not be measured at all. Distinct
#: from 1 (a real regression) so a caller can tell "it broke" from "we could not tell", and
#: distinct from 2, which Click already returns for a usage error. See ADR-0018.
EXIT_UNMEASURED = 3
#: Below this, the permutation test is underpowered — warn but proceed. Derived from the
#: config default so the number a user is warned about and the number they get by default
#: can never disagree; three copies of it drifting apart is exactly what MP-03 was.
RECOMMENDED_RUNS = DEFAULT_RUNS
#: Tool-call trajectory match modes accepted by `--match` (validated at the CLI boundary
#: so an unknown mode fails friendly here rather than deep in the diff engine).
VALID_MATCH_MODES = ("strict", "unordered", "subset", "superset")

app = typer.Typer(
    help="Modelpin - Dependabot for AI models. Know before the model breaks you.",
    no_args_is_help=True,
    add_completion=False,
    rich_markup_mode=None,  # plain Click help: ASCII-only, never crashes on cp1252
)
console = Console()

_SAMPLE_SCENARIO = """{
  "id": "greeting",
  "name": "Simple greeting",
  "kind": "single",
  "input": {"messages": [{"role": "user", "content": "Say hello in one short sentence."}]},
  "assertions": {"must_contain": ["hello"]}
}
"""

# The scaffolded `runs:` is interpolated from DEFAULT_RUNS, not typed literally: the
# scaffold, the config default and the CLI warning were three copies of one number that
# drifted apart, which IS MP-03.
_SAMPLE_CONFIG = f"""# modelpin.yaml - generated by `modelpin init`. See docs/ for the full reference.
models:
  - gpt-4o-mini            # the model your app currently depends on (set yours)
scenarios_dir: scenarios
providers:
  - openai                 # uses YOUR OPENAI_API_KEY from the environment
runs: {DEFAULT_RUNS}                    # N replays per scenario; below 4 the tool signal cannot fire
judge_model: gpt-4o-mini   # semantic LLM-judge (optional; extra calls). Remove to disable.
"""


def _fail(message: str) -> NoReturn:
    console.print(f"[red]error:[/] {message}")
    raise typer.Exit(code=1)


def _adapter(provider: str, fixtures: Optional[str]) -> ProviderAdapter:
    try:
        if provider == "fake":
            return FakeProvider.from_fixtures(fixtures) if fixtures else FakeProvider()
        return get_adapter(provider)
    except FileNotFoundError as exc:
        _fail(f"fixtures file not found: {exc}")
    except ValueError as exc:  # unknown provider
        _fail(str(exc))


def _unimplemented_msg(provider: str) -> str:
    return (
        f"the {provider!r} adapter isn't implemented yet. Try `--provider fake "
        "--fixtures <file>` to run offline, or pick `--provider openai`."
    )


def _preflight_or_fail(adapter: ProviderAdapter, provider: str) -> None:
    """Fail before any tokens are spent if the provider isn't ready (key/SDK)."""
    try:
        adapter.preflight()
    except ProviderError as exc:
        _fail(str(exc))


def _guard_replay(provider: str, fn):
    """Run a replay step, converting adapter failures into friendly CLI errors."""
    try:
        return fn()
    except NotImplementedError:
        _fail(_unimplemented_msg(provider))
    except ProviderError as exc:
        _fail(str(exc))


def _replay_plan(
    count: int,
    src_dir: str,
    runs: int,
    provider: str,
    judge_model: Optional[str],
    sides: int = 1,
) -> str:
    """Describe the size of the run that is ABOUT to happen, for the pre-spend line.

    The `>=` is load-bearing and must not be "tidied" into an exact count: one replay is one
    `adapter.run()`, but an agent scenario's replay drives a tool loop of up to
    `MAX_TOOL_TURNS` completions, so replays FLOOR the paid calls and never cap them.
    ADR-0019 governs this contract, including why `fake` must claim no cost at all.

    `sides` is how many models are replayed LIVE: 1 for `baseline`/`check`, whose reference
    traces come off disk, and 2 for `report`, which replays `--from` and `--to` both. It
    scales replays and therefore paid calls -- but deliberately NOT the judge axis, because
    `semantic_divergence_flags` scores every run on both sides regardless of where those
    traces came from. [M] MP-70: the same 14-scenario suite queues 70 replays under `check`
    and 140 under `report`, but discloses `up to 140 judge calls` either way. (That ceiling
    is deliberately loose: a real run needs at most 126, because an output identical to the
    modal baseline skips the judge -- `up to` is the honest word for a bound.) Deriving the
    judge count from `replays` would overstate `report`'s judge bill 2x -- the false-claim
    defect ADR-0019 rejects, merely pointed the other way.
    """
    replays = count * runs * sides
    plan = f"{count} scenario(s) from {src_dir}"
    if sides > 1:
        plan += f" x {sides} models"
    plan += f" -> {replays} replays"
    if provider == "fake":
        return plan  # canned traces, no network, nothing billed
    plan += f", >={replays} paid calls"
    if judge_model:
        plan += f" + up to {2 * count * runs} judge calls"
    return plan


def _build_judge(provider: str, cfg: ModelpinConfig):
    """Construct + preflight the semantic LLM-judge if configured. Returns None when no
    judge_model is set or the run is offline (fake), so the diff stays purely structural."""
    if not cfg.judge_model or provider == "fake":
        return None
    try:
        from modelpin.judge import build_judge

        # The judge is independent of the models being compared (the judge model id picks
        # its provider), so a cross-vendor check (e.g. google vs openai) can still judge.
        judge = build_judge(cfg.judge_model)
        judge.preflight()
    except (ProviderError, ImportError) as exc:
        _fail(f"semantic judge ({cfg.judge_model!r}): {exc}")
    console.print(f"[dim]semantic judge: {cfg.judge_model}[/]")
    return judge


def _load_config_or_fail(config_path: str) -> ModelpinConfig:
    try:
        return load_config(config_path)
    except ConfigError as exc:
        _fail(str(exc))


#: How the directory we searched was chosen — quoted back to the user, because
#: "no scenarios in 'examples/scenarios'" never said *who* asked for that path.
_SOURCE_LABEL = {
    "flag": "from --scenarios-dir",
    "config": "from scenarios_dir: in modelpin.yaml",
    "default": "the built-in default",
    "suite": "from --suite-dir",
}
_REPO_URL = "https://github.com/samarthputhraya/modelpin"


def _dir_state(p: Path) -> str:
    """Which of the states that `load_scenarios()` collapses into `[]` are we actually in?"""
    if not p.exists():
        return "that directory does not exist"
    if not p.is_dir():
        return "that path is a file, not a directory"
    jsons = sorted(p.glob("*.json"))
    if not jsons:
        return "it exists but contains no .json files"
    if all(f.name in _RESERVED_IN_DIR for f in jsons):
        names = ", ".join(f.name for f in jsons)
        return f"it contains only reserved files ({names}) and no scenario files"
    return "no .json file there loaded as a scenario"


def _init_target(config_path: str) -> Optional[Path]:
    """The scenarios dir `modelpin init` would actually create here, or None if unknowable."""
    try:
        sub = load_config(config_path).scenarios_dir if Path(config_path).exists() else "scenarios"
    except ConfigError:
        return None
    return (Path.cwd() / sub).resolve()


def _demo_hint(resolved: Path) -> str:
    """A generated demo sitting right next to the user is almost always what they meant.

    Without this, forgetting `cd modelpin-demo` sends a deliberately key-less user down the
    `modelpin init` path, which scaffolds a REAL provider config -- and the next command then
    demands a billed OPENAI_API_KEY, contradicting the "no API key" promise they just read.
    """
    for base in (Path.cwd(), resolved.parent):
        candidate = base / DEMO_DIRNAME
        if (candidate / DEMO_FIXTURES).is_file():
            return f"There is an offline demo right here: `cd {DEMO_DIRNAME}` first, then re-run. "
    return ""


def _scenarios_remedy(resolved: Path, source: str, config_path: str) -> str:
    """Advice that is TRUE in this state. `modelpin init` is only named when it would create
    exactly this path — otherwise the user follows it, succeeds, retries, and loops."""
    if source == "suite":
        return (
            "`modelpin init` does not create suite directories. The open public suite ships in "
            f"the repo, not in the wheel: clone {_REPO_URL} and pass "
            "--suite-dir <checkout>/examples/report-suite."
        )
    if resolved == _init_target(config_path):
        return _demo_hint(resolved) + (
            "Run `modelpin init` to scaffold it with a starter scenario, or "
            "`modelpin init --demo` "
            "for a runnable offline demo."
        )
    if source == "flag":
        return (
            "`modelpin init` will NOT create this path. Either add scenario *.json files there, "
            "or drop --scenarios-dir to use the directory from modelpin.yaml."
        )
    return (
        "`modelpin init` scaffolds the directory named by scenarios_dir: in modelpin.yaml, "
        "is not this path. Either add scenario *.json files here, or fix scenarios_dir:."
    )


def _fail_no_scenarios(raw: str, source: str, config_path: str) -> NoReturn:
    resolved = Path(raw).resolve()
    # _rich_escape: _fail() prints through Rich markup, so a path containing '[' would
    # otherwise be swallowed as a style tag and corrupt the very message meant to unstick
    # the user.
    _fail(
        f"no scenarios found in {_rich_escape(str(resolved))} ({_SOURCE_LABEL[source]}) -\n"
        f"       {_dir_state(Path(raw))}.\n"
        f"       {_scenarios_remedy(resolved, source, config_path)}"
    )


def _load_scenarios_or_fail(
    scenarios_dir: str, *, source: str, config_path: str = "modelpin.yaml"
) -> list[Scenario]:
    try:
        scenarios = load_scenarios(scenarios_dir)
    except ScenarioError as exc:
        _fail(str(exc))
    if not scenarios:
        _fail_no_scenarios(scenarios_dir, source, config_path)
    return scenarios


def _scenarios_source(scenarios_dir: Optional[str], config_path: str) -> str:
    """Where the scenarios directory came from, for the error message to quote back."""
    if scenarios_dir:
        return "flag"
    return "config" if Path(config_path).exists() else "default"


def _resolve_provider(provider: Optional[str], cfg: ModelpinConfig) -> str:
    return provider or (cfg.providers[0] if cfg.providers else DEFAULT_PROVIDER)


def _resolve_runs(
    runs: Optional[int],
    cfg: ModelpinConfig,
    *,
    mode: str = "strict",
    baseline_sizes: Sequence[int] | None = None,
) -> int:
    n = cfg.runs if runs is None else runs  # an explicit --runs 0 must hit the floor, not coerce
    if n < MIN_RUNS:
        _fail(
            f"--runs must be >= {MIN_RUNS}: the diff compares run *distributions*, and "
            f"a single run can't form one (got {n})."
        )
    # ADR-0019 discloses the run SIZE before a command spends. A size that cannot reach
    # ALPHA is the same disclosure one level up: the user is about to pay for a run that is
    # structurally incapable of reporting a regression, and "less power" does not say that.
    # [M] MP-55: the shipped demo at `--runs 2` printed `OK 4 scenario(s) unchanged`, exit 0,
    # and wrote "looks safe to adopt" -- where the SAME fixtures at `--runs 5` find two
    # regressions and a minor.
    #
    # Priced on BOTH sides and on the MODE, or the warning becomes the very defect it exists
    # to prevent. [M] Pricing it on the candidate alone asserted "this run cannot report a
    # regression" over `baseline --runs 5` + `check --runs 2` -- an invocation that then
    # reported two regressions and exited 1, because the real 5v2 floor is 0.047619, below
    # ALPHA. [M] And the distribution floor only gates the tool/argument signals under the
    # EQUIVALENCE modes; the directional ones route through the mean statistic
    # (`diff/__init__.py`), so warning about them under `--match subset` was simply false --
    # reproduced firing a `subset` tool-call regression in the same invocation as the warning
    # that said it could not.
    nb = min(baseline_sizes) if baseline_sizes else n
    floor = min_achievable_pvalue_mean(nb, n)
    if floor > ALPHA:
        console.print(
            f"[bold yellow]warning:[/] at {nb} vs {n} runs/side the exact permutation test "
            f"cannot return a p-value below {floor:.3f}, so NO signal can reach p <= {ALPHA}. "
            f"[bold]This run cannot report a regression[/], whatever the models do. "
            f"Use --runs {RECOMMENDED_RUNS}."
        )
    elif mode in EQUIVALENCE_MODES and min_achievable_pvalue_distribution(nb, n) > ALPHA:
        dist_floor = min_achievable_pvalue_distribution(nb, n)
        console.print(
            f"[yellow]warning:[/] at {nb} vs {n} runs/side the tool-call and argument signals "
            f"cannot reach p <= {ALPHA} under `{mode}` (their floor is {dist_floor:.3f}). The "
            f"one-sided signals — refusal, format drift and the semantic judge — reach "
            f"{floor:.3f}. Use --runs {RECOMMENDED_RUNS}."
        )
    elif n < RECOMMENDED_RUNS:
        console.print(
            f"[yellow]warning:[/] only {n} runs/scenario; {RECOMMENDED_RUNS}+ gives the "
            "statistical diff real power and a lower false-positive rate."
        )
    return n


def _resolve_match_mode(mode: str) -> str:
    if mode not in VALID_MATCH_MODES:
        _fail(f"--match must be one of {', '.join(VALID_MATCH_MODES)} (got {mode!r}).")
    return mode


@app.command()
def version() -> None:
    """Print the Modelpin version."""
    console.print(f"modelpin {__version__}")


@app.command()
def scan(path: str = typer.Argument(".", help="Repo root to scan.")) -> None:
    """Detect which AI models this repo depends on, and where."""
    hits = scan_repo(path)
    if not hits:
        console.print("No model identifiers found.")
        return
    table = Table("model", "file", "line", title="Models this repo depends on", box=ASCII_BOX)
    for h in sorted(hits, key=lambda x: (x["model"], x["file"], x["line"])):
        table.add_row(h["model"], h["file"], str(h["line"]))
    console.print(table)
    console.print(f"[dim]{len({h['model'] for h in hits})} distinct model(s).[/]")


@app.command()
def init(
    directory: str = typer.Argument(".", help="Repo to scaffold."),
    demo: bool = typer.Option(
        False,
        "--demo",
        help="Write a runnable offline demo instead of scaffolding this repo "
        "(no API key, no cost).",
    ),
) -> None:
    """Create modelpin.yaml + scenarios/ in the current repo (never overwrites)."""
    root = Path(directory)

    if demo:
        written = write_demo(root)
        if written:
            console.print("[green]Offline demo written:[/]")
            for p in written:
                console.print(f"  - {p}")
        else:
            console.print(f"[dim]{root / DEMO_DIRNAME} already exists; left untouched.[/]")
        console.print("\nNext, run these three lines:")
        console.print(f"  [bold]cd {DEMO_DIRNAME}[/]")
        console.print(f"  [bold]modelpin baseline --fixtures {DEMO_FIXTURES}[/]")
        console.print(f"  [bold]modelpin check --to {DEMO_TO} --fixtures {DEMO_FIXTURES}[/]")
        console.print(
            f"\n[dim]`modelpin check` exits 1 there on purpose - that is the CI gate. "
            f"See {DEMO_DIRNAME}/README.md.[/]"
        )
        return

    cfg_path = root / "modelpin.yaml"
    # Honour an existing modelpin.yaml's scenarios_dir. Hardcoding "scenarios" here made
    # `mp init` scaffold a directory the rest of the CLI would then not read — the second
    # no-exit loop: the error says run `mp init`, `mp init` succeeds, nothing changes.
    sub = "scenarios"
    if cfg_path.exists():
        try:
            sub = load_config(cfg_path).scenarios_dir
        except ConfigError as exc:
            _fail(str(exc))
    scenarios_dir = root / sub

    created: list[str] = []
    if not cfg_path.exists():
        cfg_path.write_text(_SAMPLE_CONFIG, encoding="utf-8")
        created.append(str(cfg_path))
    scenarios_dir.mkdir(parents=True, exist_ok=True)
    # Reserved-aware, and it must stay that way: `_dir_state()` reports a dir holding
    # only manifest.json as having no scenarios, so if this check disagrees, `init`
    # silently writes nothing and the error's advice loops forever. That is the exact
    # defect class MP-01 was about, reintroduced one function away.
    existing = [f for f in scenarios_dir.glob("*.json") if f.name not in _RESERVED_IN_DIR]
    if not existing:
        (scenarios_dir / "greeting.json").write_text(_SAMPLE_SCENARIO, encoding="utf-8")
        created.append(str(scenarios_dir / "greeting.json"))
    if created:
        console.print("[green]Scaffolded:[/]")
        for c in created:
            console.print(f"  - {c}")
        console.print("\nNext: add scenarios, then run [bold]modelpin baseline[/].")
        console.print(
            "[dim]No API key yet? Run `modelpin init --demo` for a free offline walkthrough.[/]"
        )
    else:
        # MP-32: this branch means `init` ADOPTED a config it did not write. Reporting a bare
        # "already initialised" let a cloned repo's config hand the user a scenario set they
        # had never seen, which `baseline` then replayed on their key. Name what was adopted.
        # `existing` is not stale here: this branch means nothing was created, so no
        # greeting.json was written after the glob.
        console.print(f"Already initialised (modelpin.yaml + {sub}/ present).")
        console.print(
            f"[dim]{len(existing)} scenario(s) in {sub}/ - `modelpin baseline` replays "
            f"all of them on your own key. Not yours? Check {cfg_path}.[/]"
        )


@app.command()
def baseline(
    model: Optional[str] = typer.Option(
        None, "--model", help="Model to baseline (default: config)."
    ),
    provider: Optional[str] = typer.Option(
        None, "--provider", help="openai | google | anthropic | groq | openrouter | fake."
    ),
    fixtures: Optional[str] = typer.Option(
        None, "--fixtures", help="Canned traces for --provider fake (required with it)."
    ),
    runs: Optional[int] = typer.Option(None, "--runs", help="Replays per scenario."),
    config_path: str = typer.Option("modelpin.yaml", "--config"),
    scenarios_dir: Optional[str] = typer.Option(None, "--scenarios-dir"),
    store_dir: str = typer.Option(STORE_DIRNAME, "--store-dir"),
) -> None:
    """Record current model behavior for your scenarios (N runs)."""
    cfg = _load_config_or_fail(config_path)
    src_dir = scenarios_dir or cfg.scenarios_dir
    scenarios = _load_scenarios_or_fail(
        src_dir,
        source=_scenarios_source(scenarios_dir, config_path),
        config_path=config_path,
    )
    from_model = model or (cfg.models[0] if cfg.models else None)
    if not from_model:
        _fail("no model to baseline. Pass --model or set `models:` in modelpin.yaml.")
    n = _resolve_runs(runs, cfg)
    prov = _resolve_provider(provider, cfg)
    adapter = _adapter(prov, fixtures)
    plan = _replay_plan(len(scenarios), src_dir, n, prov, judge_model=None)
    console.print(f"[dim]provider={prov} model={from_model} runs={n} | {plan}[/]")
    _preflight_or_fail(adapter, prov)
    traces = _guard_replay(
        prov, lambda: {s.id: replay(s, from_model, adapter, runs=n) for s in scenarios}
    )
    path = save_baseline(traces, from_model, store_dir)
    console.print(
        f"[green]Baseline recorded[/] for [bold]{from_model}[/]: "
        f"{len(scenarios)} scenario(s) x{n} runs -> {path}"
    )


@app.command()
def check(
    to: str = typer.Option(..., "--to", help="The new model id to test against your baseline."),
    from_: Optional[str] = typer.Option(None, "--from", help="Baseline model (default: config)."),
    provider: Optional[str] = typer.Option(
        None, "--provider", help="openai | google | anthropic | groq | openrouter | fake."
    ),
    fixtures: Optional[str] = typer.Option(
        None, "--fixtures", help="Canned traces for --provider fake (required with it)."
    ),
    runs: Optional[int] = typer.Option(None, "--runs", help="Replays per scenario."),
    mode: str = typer.Option(
        "strict", "--match", help="Tool-call match mode: strict|unordered|subset|superset."
    ),
    config_path: str = typer.Option("modelpin.yaml", "--config"),
    scenarios_dir: Optional[str] = typer.Option(None, "--scenarios-dir"),
    store_dir: str = typer.Option(STORE_DIRNAME, "--store-dir"),
) -> None:
    """Replay scenarios on a new model and report behavioral regressions."""
    mode = _resolve_match_mode(mode)
    cfg = _load_config_or_fail(config_path)
    src_dir = scenarios_dir or cfg.scenarios_dir
    scenarios = _load_scenarios_or_fail(
        src_dir,
        source=_scenarios_source(scenarios_dir, config_path),
        config_path=config_path,
    )
    from_model = from_ or (cfg.models[0] if cfg.models else None)
    if not from_model:
        _fail("no baseline model. Pass --from or set `models:` in modelpin.yaml.")
    try:
        base = load_baseline(from_model, store_dir)
    except FileNotFoundError as e:
        _fail(str(e))
    except BaselineError as e:
        _fail(str(e))
    n = _resolve_runs(runs, cfg, mode=mode, baseline_sizes=[len(v) for v in base.values() if v])
    prov = _resolve_provider(provider, cfg)
    adapter = _adapter(prov, fixtures)
    # Only scenarios that HAVE a baseline are replayed (the rest are skipped below), so
    # count those - an inflated pre-spend number is its own kind of false claim. MP-32.
    billable = sum(1 for s in scenarios if base.get(s.id))
    plan = _replay_plan(billable, src_dir, n, prov, cfg.judge_model)
    console.print(
        f"[dim]provider={prov} from={from_model} to={to} runs={n} match={mode} | {plan}[/]"
    )
    _preflight_or_fail(adapter, prov)
    judge = _build_judge(prov, cfg)

    results = []
    skipped: list[str] = []

    def _run_check() -> None:
        for s in scenarios:
            base_traces = base.get(s.id)
            if not base_traces:
                skipped.append(s.id)
                continue
            cand = replay(s, to, adapter, runs=n)
            results.append(
                diff_scenario(s.id, from_model, to, base_traces, cand, s, mode, judge=judge)
            )

    _guard_replay(prov, _run_check)

    if not results:
        _fail("nothing to compare. Record a baseline first with `modelpin baseline`.")

    # MP-55. Which scenarios were compared at run counts where NO signal could reach ALPHA?
    # Computed per scenario, because a stored baseline can hold a different number of runs
    # than `--runs` gives the candidate (`baseline --runs 5` then `check --runs 2` is 5v2),
    # and the permutation floor depends on BOTH sides.
    def _blind(sid: str) -> bool:
        nb = len(base[sid])
        if min_achievable_pvalue_mean(nb, n) > ALPHA:
            return True  # no signal at all could have fired
        # [M] And the narrower trap, which is a MORE confident false clearance than the one
        # above: at 3v3 `strict` the demo's `refund_request` -- whose only change is the
        # tool-call trajectory -- rendered `✅ no behavioral change` and "looks safe to adopt",
        # while N=4 on identical fixtures reports a regression. The equivalence modes route
        # the tool and argument signals through the two-sided test, whose floor is higher.
        return mode in EQUIVALENCE_MODES and min_achievable_pvalue_distribution(nb, n) > ALPHA

    underpowered = [s.id for s in scenarios if base.get(s.id) and _blind(s.id)]

    console.print(render_cli(results, from_model, to, n, underpowered))

    # Decide the CI exit code BEFORE any side effect, so a report-write failure
    # can never silently mask a real regression.
    has_regression = any(r.verdict == DiffVerdict.regression for r in results)
    unmeasured = [r for r in results if r.verdict == DiffVerdict.insufficient_evidence]

    report_path = Path(store_dir) / "last-report.md"
    try:
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(
            render_pr_comment(results, from_model, to, n, prov, underpowered),
            encoding="utf-8",
        )
        console.print(f"\n[dim]PR-style Markdown report written to {report_path}[/]")
    except OSError as exc:
        console.print(f"[yellow]warning:[/] could not write report to {report_path}: {exc}")

    if skipped:
        console.print(
            f"[yellow]note:[/] {len(skipped)} scenario(s) had no baseline and were skipped: "
            f"{', '.join(skipped)}. Re-run `modelpin baseline` to cover them."
        )

    if has_regression:
        raise typer.Exit(code=1)  # fail CI on a real regression
    if unmeasured:
        # EXIT_UNMEASURED, not 1: a run that measured nothing is not a regression, and
        # reporting it as one would put a false claim in the Action's PR comment. Not 2
        # either -- Click already uses 2 for a usage error, so `mp check --bogus` exits 2.
        # The Action gates on `code != '0'`, so CI still fails without any workflow change.
        raise typer.Exit(code=EXIT_UNMEASURED)


#: Where rendered Modelpin Reports (.md + .json) are written by default.
#: There is deliberately no DEFAULT_REPORT_SUITE: the wheel ships no scenarios at all,
#: so any built-in default would name a path that cannot exist after `pip install`, and the
#: user would be told "no scenarios found" for a directory they never asked for.
DEFAULT_REPORT_OUTPUT = "reports"


def _report_basename(candidate: str, reference: str, date_iso: str) -> str:
    """Deterministic report filename stem. Same-model runs drop the `-vs-` segment."""
    if candidate == reference:
        return f"modelpin-report-{slug(candidate)}-{date_iso}"
    return f"modelpin-report-{slug(candidate)}-vs-{slug(reference)}-{date_iso}"


@app.command()
def report(
    to: str = typer.Option(..., "--to", help="The new/launching model id to report on."),
    from_: str = typer.Option(
        ...,
        "--from",
        help="Reference/incumbent model to compare against (pass the same id as --to for a "
        "baseline characterization).",
    ),
    provider: Optional[str] = typer.Option(
        None, "--provider", help="openai | google | anthropic | groq | openrouter | fake."
    ),
    fixtures: Optional[str] = typer.Option(
        None, "--fixtures", help="Canned traces for --provider fake (required with it)."
    ),
    runs: Optional[int] = typer.Option(None, "--runs", help="Replays per scenario per model."),
    mode: str = typer.Option(
        "strict", "--match", help="Tool-call match mode: strict|unordered|subset|superset."
    ),
    suite_dir: str = typer.Option(
        ...,
        "--suite-dir",
        help="Public scenario suite directory (required; the open suite lives in the repo).",
    ),
    config_path: str = typer.Option("modelpin.yaml", "--config"),
    output_dir: str = typer.Option(
        DEFAULT_REPORT_OUTPUT, "--output-dir", help="Directory for the .md + .json report."
    ),
) -> None:
    """Run the open public suite across two models and draft a reproducible Modelpin Report.

    Unlike `modelpin check`, this never fails CI on a regression — it *publishes* findings. Both
    models are replayed live with YOUR API key (BYO-key); the report is framed as
    measurement/opinion ("on our open suite, under these settings, we observed…").
    """
    mode = _resolve_match_mode(mode)
    cfg = _load_config_or_fail(config_path)
    scenarios = _load_scenarios_or_fail(suite_dir, source="suite", config_path=config_path)
    n = _resolve_runs(runs, cfg)
    prov = _resolve_provider(provider, cfg)
    adapter = _adapter(prov, fixtures)
    # Both sides are replayed live here, so the run is twice the size of a `check` over the
    # same suite -- and this is the user's own key (ADR-0008). Disclose before spending it.
    plan = _replay_plan(len(scenarios), suite_dir, n, prov, cfg.judge_model, sides=2)
    console.print(f"[dim]provider={prov} from={from_} to={to} runs={n} match={mode} | {plan}[/]")
    _preflight_or_fail(adapter, prov)
    judge = _build_judge(prov, cfg)

    results: list[DiffResult] = []
    skipped: list[str] = []
    for s in scenarios:
        try:
            base_traces = replay(s, from_, adapter, runs=n)
            cand_traces = replay(s, to, adapter, runs=n)
        except NotImplementedError:
            _fail(
                _unimplemented_msg(prov)
            )  # an unimplemented adapter is a config error, not a skip
        except ProviderError as exc:
            # One scenario failing must not sink the whole report — it documents findings.
            # ProviderError messages are already key-scrubbed by the adapters.
            console.print(f"[yellow]note:[/] scenario {s.id!r} skipped: {exc}")
            skipped.append(s.id)
            continue
        results.append(
            diff_scenario(s.id, from_, to, base_traces, cand_traces, s, mode, judge=judge)
        )

    if not results:
        _fail("no scenarios completed; nothing to report.")

    console.print(render_cli(results, from_, to, n))

    suite_id, suite_version = read_manifest(suite_dir)
    date_iso = datetime.now(timezone.utc).date().isoformat()
    # Shell-quote each value so the copy-paste reproduce command survives model ids or paths
    # containing spaces/parentheses (POSIX quoting, for the bash/CI context the tool targets).
    reproduce_cmd = (
        f"modelpin report --to {shlex.quote(to)} --from {shlex.quote(from_)} "
        f"--provider {shlex.quote(prov)} --runs {n} --match {shlex.quote(mode)} "
        f"--suite-dir {shlex.quote(suite_dir)}"
    )
    meta = ReportMeta(
        suite_id=suite_id,
        suite_version=suite_version,
        suite_hash=compute_suite_hash(scenarios),
        suite_path=suite_dir,
        candidate_model=to,
        reference_model=from_,
        provider=prov,
        runs=n,
        judge_model=cfg.judge_model if judge is not None else "disabled",
        match_mode=mode,
        modelpin_version=__version__,
        diff_thresholds={
            "alpha": ALPHA,
            "min_tool_tvd": MIN_TOOL_TVD,
            # ADR-0009: a public Report must publish every floor that gated a verdict in it.
            # The argument floor is advisory-only (ADR-0029) but it still GATES -- omitting it
            # hands the reader an `Arg match` number and a `changed_minor` verdict with no way
            # to tell which threshold produced them.
            "min_tool_arg_tvd": MIN_TOOL_ARG_TVD,
            "min_refusal_delta": MIN_REFUSAL_DELTA,
            "min_semantic_delta": MIN_SEMANTIC_DELTA,
        },
        date_iso=date_iso,
        reproduce_cmd=reproduce_cmd,
        scenario_ids=[s.id for s in scenarios],
        skipped=skipped,
    )

    out = Path(output_dir)
    base = _report_basename(to, from_, date_iso)
    md_path = out / f"{base}.md"
    json_path = out / f"{base}.json"
    try:
        out.mkdir(parents=True, exist_ok=True)
        md_path.write_text(render_report_md(results, meta), encoding="utf-8")
        json_path.write_text(
            json.dumps(to_report_sidecar(results, meta), indent=2), encoding="utf-8"
        )
        console.print(f"\n[green]Modelpin Report written[/] -> {md_path}")
        console.print(f"[dim]raw results (JSON) -> {json_path}[/]")
    except OSError as exc:
        console.print(f"[yellow]warning:[/] could not write report to {out}: {exc}")

    if skipped:
        console.print(
            f"[yellow]note:[/] {len(skipped)} scenario(s) skipped and excluded from the "
            f"report counts: {', '.join(skipped)}."
        )
    # NB: report() never exits non-zero on a regression — it publishes findings, not a CI gate.


def main() -> None:
    app()


if __name__ == "__main__":
    main()
